import {type I18n} from '@lingui/core'
import {msg} from '@lingui/macro'

export function getCountriesWithTelephoneCodes(i18n: I18n) {
  return {
    AD: {
      name: i18n._(msg`Andorra`),
      code: '+376',
      unicodeFlag: '🇦🇩',
      svgFlag: require('../../assets/icons/flags/AD.svg'),
    },
    AF: {
      name: i18n._(msg`Afghanistan`),
      code: '+93',
      unicodeFlag: '🇦🇫',
      svgFlag: require('../../assets/icons/flags/AF.svg'),
    },
    AG: {
      name: i18n._(msg`Antigua and Barbuda`),
      code: '+1268',
      unicodeFlag: '🇦🇬',
      svgFlag: require('../../assets/icons/flags/AG.svg'),
    },
    AI: {
      name: i18n._(msg`Anguilla`),
      code: '+1264',
      unicodeFlag: '🇦🇮',
      svgFlag: require('../../assets/icons/flags/AI.svg'),
    },
    AL: {
      name: i18n._(msg`Albania`),
      code: '+355',
      unicodeFlag: '🇦🇱',
      svgFlag: require('../../assets/icons/flags/AL.svg'),
    },
    AM: {
      name: i18n._(msg`Armenia`),
      code: '+374',
      unicodeFlag: '🇦🇲',
      svgFlag: require('../../assets/icons/flags/AM.svg'),
    },
    AO: {
      name: i18n._(msg`Angola`),
      code: '+244',
      unicodeFlag: '🇦🇴',
      svgFlag: require('../../assets/icons/flags/AO.svg'),
    },
    AQ: {
      name: i18n._(msg`Antarctica`),
      code: '+672',
      unicodeFlag: '🇦🇶',
      svgFlag: require('../../assets/icons/flags/AQ.svg'),
    },
    AR: {
      name: i18n._(msg`Argentina`),
      code: '+54',
      unicodeFlag: '🇦🇷',
      svgFlag: require('../../assets/icons/flags/AR.svg'),
    },
    AS: {
      name: i18n._(msg`American Samoa`),
      code: '+1684',
      unicodeFlag: '🇦🇸',
      svgFlag: require('../../assets/icons/flags/AS.svg'),
    },
    AT: {
      name: i18n._(msg`Austria`),
      code: '+43',
      unicodeFlag: '🇦🇹',
      svgFlag: require('../../assets/icons/flags/AT.svg'),
    },
    AU: {
      name: i18n._(msg`Australia`),
      code: '+61',
      unicodeFlag: '🇦🇺',
      svgFlag: require('../../assets/icons/flags/AU.svg'),
    },
    AW: {
      name: i18n._(msg`Aruba`),
      code: '+297',
      unicodeFlag: '🇦🇼',
      svgFlag: require('../../assets/icons/flags/AW.svg'),
    },
    AX: {
      name: i18n._(msg`Åland Islands`),
      code: '+358',
      unicodeFlag: '🇦🇽',
      svgFlag: require('../../assets/icons/flags/AX.svg'),
    },
    AZ: {
      name: i18n._(msg`Azerbaijan`),
      code: '+994',
      unicodeFlag: '🇦🇿',
      svgFlag: require('../../assets/icons/flags/AZ.svg'),
    },
    BA: {
      name: i18n._(msg`Bosnia and Herzegovina`),
      code: '+387',
      unicodeFlag: '🇧🇦',
      svgFlag: require('../../assets/icons/flags/BA.svg'),
    },
    BB: {
      name: i18n._(msg`Barbados`),
      code: '+1246',
      unicodeFlag: '🇧🇧',
      svgFlag: require('../../assets/icons/flags/BB.svg'),
    },
    BD: {
      name: i18n._(msg`Bangladesh`),
      code: '+880',
      unicodeFlag: '🇧🇩',
      svgFlag: require('../../assets/icons/flags/BD.svg'),
    },
    BE: {
      name: i18n._(msg`Belgium`),
      code: '+32',
      unicodeFlag: '🇧🇪',
      svgFlag: require('../../assets/icons/flags/BE.svg'),
    },
    BF: {
      name: i18n._(msg`Burkina Faso`),
      code: '+226',
      unicodeFlag: '🇧🇫',
      svgFlag: require('../../assets/icons/flags/BF.svg'),
    },
    BG: {
      name: i18n._(msg`Bulgaria`),
      code: '+359',
      unicodeFlag: '🇧🇬',
      svgFlag: require('../../assets/icons/flags/BG.svg'),
    },
    BH: {
      name: i18n._(msg`Bahrain`),
      code: '+973',
      unicodeFlag: '🇧🇭',
      svgFlag: require('../../assets/icons/flags/BH.svg'),
    },
    BI: {
      name: i18n._(msg`Burundi`),
      code: '+257',
      unicodeFlag: '🇧🇮',
      svgFlag: require('../../assets/icons/flags/BI.svg'),
    },
    BJ: {
      name: i18n._(msg`Benin`),
      code: '+229',
      unicodeFlag: '🇧🇯',
      svgFlag: require('../../assets/icons/flags/BJ.svg'),
    },
    BL: {
      name: i18n._(msg`Saint Barthélemy`),
      code: '+590',
      unicodeFlag: '🇧🇱',
      svgFlag: require('../../assets/icons/flags/BL.svg'),
    },
    BM: {
      name: i18n._(msg`Bermuda`),
      code: '+1441',
      unicodeFlag: '🇧🇲',
      svgFlag: require('../../assets/icons/flags/BM.svg'),
    },
    BN: {
      name: i18n._(msg`Brunei Darussalam`),
      code: '+673',
      unicodeFlag: '🇧🇳',
      svgFlag: require('../../assets/icons/flags/BN.svg'),
    },
    BO: {
      name: i18n._(msg`Bolivia (Plurinational State of)`),
      code: '+591',
      unicodeFlag: '🇧🇴',
      svgFlag: require('../../assets/icons/flags/BO.svg'),
    },
    BQ: {
      name: i18n._(msg`Bonaire, Sint Eustatius and Saba`),
      code: '+5997',
      unicodeFlag: '🇧🇶',
      svgFlag: require('../../assets/icons/flags/BQ.svg'),
    },
    BR: {
      name: i18n._(msg`Brazil`),
      code: '+55',
      unicodeFlag: '🇧🇷',
      svgFlag: require('../../assets/icons/flags/BR.svg'),
    },
    BT: {
      name: i18n._(msg`Bhutan`),
      code: '+975',
      unicodeFlag: '🇧🇹',
      svgFlag: require('../../assets/icons/flags/BT.svg'),
    },
    BV: {
      name: i18n._(msg`Bouvet Island`),
      code: '+47',
      unicodeFlag: '🇧🇻',
      svgFlag: require('../../assets/icons/flags/BV.svg'),
    },
    BW: {
      name: i18n._(msg`Botswana`),
      code: '+267',
      unicodeFlag: '🇧🇼',
      svgFlag: require('../../assets/icons/flags/BW.svg'),
    },
    BY: {
      name: i18n._(msg`Belarus`),
      code: '+375',
      unicodeFlag: '🇧🇾',
      svgFlag: require('../../assets/icons/flags/BY.svg'),
    },
    BZ: {
      name: i18n._(msg`Belize`),
      code: '+501',
      unicodeFlag: '🇧🇿',
      svgFlag: require('../../assets/icons/flags/BZ.svg'),
    },
    CA: {
      name: i18n._(msg`Canada`),
      code: '+1',
      unicodeFlag: '🇨🇦',
      svgFlag: require('../../assets/icons/flags/CA.svg'),
    },
    CH: {
      name: i18n._(msg`Switzerland`),
      code: '+41',
      unicodeFlag: '🇨🇭',
      svgFlag: require('../../assets/icons/flags/CH.svg'),
    },
    CI: {
      name: i18n._(msg`Côte d'Ivoire`),
      code: '+225',
      unicodeFlag: '🇨🇮',
      svgFlag: require('../../assets/icons/flags/CI.svg'),
    },
    CL: {
      name: i18n._(msg`Chile`),
      code: '+56',
      unicodeFlag: '🇨🇱',
      svgFlag: require('../../assets/icons/flags/CL.svg'),
    },
    CM: {
      name: i18n._(msg`Cameroon`),
      code: '+237',
      unicodeFlag: '🇨🇲',
      svgFlag: require('../../assets/icons/flags/CM.svg'),
    },
    CN: {
      name: i18n._(msg`China`),
      code: '+86',
      unicodeFlag: '🇨🇳',
      svgFlag: require('../../assets/icons/flags/CN.svg'),
    },
    CO: {
      name: i18n._(msg`Colombia`),
      code: '+57',
      unicodeFlag: '🇨🇴',
      svgFlag: require('../../assets/icons/flags/CO.svg'),
    },
    CR: {
      name: i18n._(msg`Costa Rica`),
      code: '+506',
      unicodeFlag: '🇨🇷',
      svgFlag: require('../../assets/icons/flags/CR.svg'),
    },
    CU: {
      name: i18n._(msg`Cuba`),
      code: '+53',
      unicodeFlag: '🇨🇺',
      svgFlag: require('../../assets/icons/flags/CU.svg'),
    },
    CV: {
      name: i18n._(msg`Cabo Verde`),
      code: '+238',
      unicodeFlag: '🇨🇻',
      svgFlag: require('../../assets/icons/flags/CV.svg'),
    },
    CW: {
      name: i18n._(msg`Curaçao`),
      code: '+599',
      unicodeFlag: '🇨🇼',
      svgFlag: require('../../assets/icons/flags/CW.svg'),
    },
    CX: {
      name: i18n._(msg`Christmas Island`),
      code: '+61',
      unicodeFlag: '🇨🇽',
      svgFlag: require('../../assets/icons/flags/CX.svg'),
    },
    CY: {
      name: i18n._(msg`Cyprus`),
      code: '+357',
      unicodeFlag: '🇨🇾',
      svgFlag: require('../../assets/icons/flags/CY.svg'),
    },
    DE: {
      name: i18n._(msg`Germany`),
      code: '+49',
      unicodeFlag: '🇩🇪',
      svgFlag: require('../../assets/icons/flags/DE.svg'),
    },
    DJ: {
      name: i18n._(msg`Djibouti`),
      code: '+253',
      unicodeFlag: '🇩🇯',
      svgFlag: require('../../assets/icons/flags/DJ.svg'),
    },
    DK: {
      name: i18n._(msg`Denmark`),
      code: '+45',
      unicodeFlag: '🇩🇰',
      svgFlag: require('../../assets/icons/flags/DK.svg'),
    },
    DM: {
      name: i18n._(msg`Dominica`),
      code: '+767',
      unicodeFlag: '🇩🇲',
      svgFlag: require('../../assets/icons/flags/DM.svg'),
    },
    DZ: {
      name: i18n._(msg`Algeria`),
      code: '+213',
      unicodeFlag: '🇩🇿',
      svgFlag: require('../../assets/icons/flags/DZ.svg'),
    },
    EC: {
      name: i18n._(msg`Ecuador`),
      code: '+593',
      unicodeFlag: '🇪🇨',
      svgFlag: require('../../assets/icons/flags/EC.svg'),
    },
    EE: {
      name: i18n._(msg`Estonia`),
      code: '+372',
      unicodeFlag: '🇪🇪',
      svgFlag: require('../../assets/icons/flags/EE.svg'),
    },
    EG: {
      name: i18n._(msg`Egypt`),
      code: '+20',
      unicodeFlag: '🇪🇬',
      svgFlag: require('../../assets/icons/flags/EG.svg'),
    },
    EH: {
      name: i18n._(msg`Western Sahara`),
      code: '+212',
      unicodeFlag: '🇪🇭',
      svgFlag: require('../../assets/icons/flags/EH.svg'),
    },
    ER: {
      name: i18n._(msg`Eritrea`),
      code: '+291',
      unicodeFlag: '🇪🇷',
      svgFlag: require('../../assets/icons/flags/ER.svg'),
    },
    ES: {
      name: i18n._(msg`Spain`),
      code: '+34',
      unicodeFlag: '🇪🇸',
      svgFlag: require('../../assets/icons/flags/ES.svg'),
    },
    ET: {
      name: i18n._(msg`Ethiopia`),
      code: '+251',
      unicodeFlag: '🇪🇹',
      svgFlag: require('../../assets/icons/flags/ET.svg'),
    },
    FI: {
      name: i18n._(msg`Finland`),
      code: '+358',
      unicodeFlag: '🇫🇮',
      svgFlag: require('../../assets/icons/flags/FI.svg'),
    },
    FJ: {
      name: i18n._(msg`Fiji`),
      code: '+679',
      unicodeFlag: '🇫🇯',
      svgFlag: require('../../assets/icons/flags/FJ.svg'),
    },
    FM: {
      name: i18n._(msg`Micronesia (Federated States of)`),
      code: '+691',
      unicodeFlag: '🇫🇲',
      svgFlag: require('../../assets/icons/flags/FM.svg'),
    },
    FR: {
      name: i18n._(msg`France`),
      code: '+33',
      unicodeFlag: '🇫🇷',
      svgFlag: require('../../assets/icons/flags/FR.svg'),
    },
    GA: {
      name: i18n._(msg`Gabon`),
      code: '+241',
      unicodeFlag: '🇬🇦',
      svgFlag: require('../../assets/icons/flags/GA.svg'),
    },
    GD: {
      name: i18n._(msg`Grenada`),
      code: '+1473',
      unicodeFlag: '🇬🇩',
      svgFlag: require('../../assets/icons/flags/GD.svg'),
    },
    GE: {
      name: i18n._(msg`Georgia`),
      code: '+995',
      unicodeFlag: '🇬🇪',
      svgFlag: require('../../assets/icons/flags/GE.svg'),
    },
    GF: {
      name: i18n._(msg`French Guiana`),
      code: '+594',
      unicodeFlag: '🇬🇫',
      svgFlag: require('../../assets/icons/flags/GF.svg'),
    },
    GG: {
      name: i18n._(msg`Guernsey`),
      code: '+44',
      unicodeFlag: '🇬🇬',
      svgFlag: require('../../assets/icons/flags/GG.svg'),
    },
    GH: {
      name: i18n._(msg`Ghana`),
      code: '+233',
      unicodeFlag: '🇬🇭',
      svgFlag: require('../../assets/icons/flags/GH.svg'),
    },
    GI: {
      name: i18n._(msg`Gibraltar`),
      code: '+350',
      unicodeFlag: '🇬🇮',
      svgFlag: require('../../assets/icons/flags/GI.svg'),
    },
    GL: {
      name: i18n._(msg`Greenland`),
      code: '+299',
      unicodeFlag: '🇬🇱',
      svgFlag: require('../../assets/icons/flags/GL.svg'),
    },
    GN: {
      name: i18n._(msg`Guinea`),
      code: '+224',
      unicodeFlag: '🇬🇳',
      svgFlag: require('../../assets/icons/flags/GN.svg'),
    },
    GP: {
      name: i18n._(msg`Guadeloupe`),
      code: '+590',
      unicodeFlag: '🇬🇵',
      svgFlag: require('../../assets/icons/flags/GP.svg'),
    },
    GQ: {
      name: i18n._(msg`Equatorial Guinea`),
      code: '+240',
      unicodeFlag: '🇬🇶',
      svgFlag: require('../../assets/icons/flags/GQ.svg'),
    },
    GR: {
      name: i18n._(msg`Greece`),
      code: '+30',
      unicodeFlag: '🇬🇷',
      svgFlag: require('../../assets/icons/flags/GR.svg'),
    },
    GS: {
      name: i18n._(msg`South Georgia and the South Sandwich Islands`),
      code: '+500',
      unicodeFlag: '🇬🇸',
      svgFlag: require('../../assets/icons/flags/GS.svg'),
    },
    GT: {
      name: i18n._(msg`Guatemala`),
      code: '+502',
      unicodeFlag: '🇬🇹',
      svgFlag: require('../../assets/icons/flags/GT.svg'),
    },
    GU: {
      name: i18n._(msg`Guam`),
      code: '+1',
      unicodeFlag: '🇬🇺',
      svgFlag: require('../../assets/icons/flags/GU.svg'),
    },
    GW: {
      name: i18n._(msg`Guinea-Bissau`),
      code: '+245',
      unicodeFlag: '🇬🇼',
      svgFlag: require('../../assets/icons/flags/GW.svg'),
    },
    GY: {
      name: i18n._(msg`Guyana`),
      code: '+592',
      unicodeFlag: '🇬🇾',
      svgFlag: require('../../assets/icons/flags/GY.svg'),
    },
    HK: {
      name: i18n._(msg`Hong Kong`),
      code: '+852',
      unicodeFlag: '🇭🇰',
      svgFlag: require('../../assets/icons/flags/HK.svg'),
    },
    HN: {
      name: i18n._(msg`Honduras`),
      code: '+504',
      unicodeFlag: '🇭🇳',
      svgFlag: require('../../assets/icons/flags/HN.svg'),
    },
    HR: {
      name: i18n._(msg`Croatia`),
      code: '+385',
      unicodeFlag: '🇭🇷',
      svgFlag: require('../../assets/icons/flags/HR.svg'),
    },
    HT: {
      name: i18n._(msg`Haiti`),
      code: '+509',
      unicodeFlag: '🇭🇹',
      svgFlag: require('../../assets/icons/flags/HT.svg'),
    },
    HU: {
      name: i18n._(msg`Hungary`),
      code: '+36',
      unicodeFlag: '🇭🇺',
      svgFlag: require('../../assets/icons/flags/HU.svg'),
    },
    ID: {
      name: i18n._(msg`Indonesia`),
      code: '+62',
      unicodeFlag: '🇮🇩',
      svgFlag: require('../../assets/icons/flags/ID.svg'),
    },
    IE: {
      name: i18n._(msg`Ireland`),
      code: '+353',
      unicodeFlag: '🇮🇪',
      svgFlag: require('../../assets/icons/flags/IE.svg'),
    },
    IL: {
      name: i18n._(msg`Israel`),
      code: '+972',
      unicodeFlag: '🇮🇱',
      svgFlag: require('../../assets/icons/flags/IL.svg'),
    },
    IM: {
      name: i18n._(msg`Isle of Man`),
      code: '+44',
      unicodeFlag: '🇮🇲',
      svgFlag: require('../../assets/icons/flags/IM.svg'),
    },
    IN: {
      name: i18n._(msg`India`),
      code: '+91',
      unicodeFlag: '🇮🇳',
      svgFlag: require('../../assets/icons/flags/IN.svg'),
    },
    IO: {
      name: i18n._(msg`British Indian Ocean Territory`),
      code: '+246',
      unicodeFlag: '🇮🇴',
      svgFlag: require('../../assets/icons/flags/IO.svg'),
    },
    IQ: {
      name: i18n._(msg`Iraq`),
      code: '+964',
      unicodeFlag: '🇮🇶',
      svgFlag: require('../../assets/icons/flags/IQ.svg'),
    },
    IR: {
      name: i18n._(msg`Iran (Islamic Republic of)`),
      code: '+98',
      unicodeFlag: '🇮🇷',
      svgFlag: require('../../assets/icons/flags/IR.svg'),
    },
    IS: {
      name: i18n._(msg`Iceland`),
      code: '+354',
      unicodeFlag: '🇮🇸',
      svgFlag: require('../../assets/icons/flags/IS.svg'),
    },
    IT: {
      name: i18n._(msg`Italy`),
      code: '+39',
      unicodeFlag: '🇮🇹',
      svgFlag: require('../../assets/icons/flags/IT.svg'),
    },
    JE: {
      name: i18n._(msg`Jersey`),
      code: '+44',
      unicodeFlag: '🇯🇪',
      svgFlag: require('../../assets/icons/flags/JE.svg'),
    },
    JM: {
      name: i18n._(msg`Jamaica`),
      code: '+876',
      unicodeFlag: '🇯🇲',
      svgFlag: require('../../assets/icons/flags/JM.svg'),
    },
    JO: {
      name: i18n._(msg`Jordan`),
      code: '+962',
      unicodeFlag: '🇯🇴',
      svgFlag: require('../../assets/icons/flags/JO.svg'),
    },
    JP: {
      name: i18n._(msg`Japan`),
      code: '+81',
      unicodeFlag: '🇯🇵',
      svgFlag: require('../../assets/icons/flags/JP.svg'),
    },
    KE: {
      name: i18n._(msg`Kenya`),
      code: '+254',
      unicodeFlag: '🇰🇪',
      svgFlag: require('../../assets/icons/flags/KE.svg'),
    },
    KG: {
      name: i18n._(msg`Kyrgyzstan`),
      code: '+996',
      unicodeFlag: '🇰🇬',
      svgFlag: require('../../assets/icons/flags/KG.svg'),
    },
    KH: {
      name: i18n._(msg`Cambodia`),
      code: '+855',
      unicodeFlag: '🇰🇭',
      svgFlag: require('../../assets/icons/flags/KH.svg'),
    },
    KP: {
      name: i18n._(msg`North Korea`),
      code: '+850',
      unicodeFlag: '🇰🇵',
      svgFlag: require('../../assets/icons/flags/KP.svg'),
    },
    KR: {
      name: i18n._(msg`South Korea`),
      code: '+82',
      unicodeFlag: '🇰🇷',
      svgFlag: require('../../assets/icons/flags/KR.svg'),
    },
    KI: {
      name: i18n._(msg`Kiribati`),
      code: '+686',
      unicodeFlag: '🇰🇮',
      svgFlag: require('../../assets/icons/flags/KI.svg'),
    },
    KN: {
      name: i18n._(msg`Saint Kitts and Nevis`),
      code: '+1869',
      unicodeFlag: '🇰🇳',
      svgFlag: require('../../assets/icons/flags/KN.svg'),
    },
    KW: {
      name: i18n._(msg`Kuwait`),
      code: '+965',
      unicodeFlag: '🇰🇼',
      svgFlag: require('../../assets/icons/flags/KW.svg'),
    },
    KZ: {
      name: i18n._(msg`Kazakhstan`),
      code: '+7',
      unicodeFlag: '🇰🇿',
      svgFlag: require('../../assets/icons/flags/KZ.svg'),
    },
    LB: {
      name: i18n._(msg`Lebanon`),
      code: '+961',
      unicodeFlag: '🇱🇧',
      svgFlag: require('../../assets/icons/flags/LB.svg'),
    },
    LC: {
      name: i18n._(msg`Saint Lucia`),
      code: '+1758',
      unicodeFlag: '🇱🇨',
      svgFlag: require('../../assets/icons/flags/LC.svg'),
    },
    LI: {
      name: i18n._(msg`Liechtenstein`),
      code: '+423',
      unicodeFlag: '🇱🇮',
      svgFlag: require('../../assets/icons/flags/LI.svg'),
    },
    LK: {
      name: i18n._(msg`Sri Lanka`),
      code: '+94',
      unicodeFlag: '🇱🇰',
      svgFlag: require('../../assets/icons/flags/LK.svg'),
    },
    LR: {
      name: i18n._(msg`Liberia`),
      code: '+231',
      unicodeFlag: '🇱🇷',
      svgFlag: require('../../assets/icons/flags/LR.svg'),
    },
    LS: {
      name: i18n._(msg`Lesotho`),
      code: '+266',
      unicodeFlag: '🇱🇸',
      svgFlag: require('../../assets/icons/flags/LS.svg'),
    },
    LT: {
      name: i18n._(msg`Lithuania`),
      code: '+370',
      unicodeFlag: '🇱🇹',
      svgFlag: require('../../assets/icons/flags/LT.svg'),
    },
    LU: {
      name: i18n._(msg`Luxembourg`),
      code: '+352',
      unicodeFlag: '🇱🇺',
      svgFlag: require('../../assets/icons/flags/LU.svg'),
    },
    LV: {
      name: i18n._(msg`Latvia`),
      code: '+371',
      unicodeFlag: '🇱🇻',
      svgFlag: require('../../assets/icons/flags/LV.svg'),
    },
    LY: {
      name: i18n._(msg`Libya`),
      code: '+218',
      unicodeFlag: '🇱🇾',
      svgFlag: require('../../assets/icons/flags/LY.svg'),
    },
    MA: {
      name: i18n._(msg`Morocco`),
      code: '+212',
      unicodeFlag: '🇲🇦',
      svgFlag: require('../../assets/icons/flags/MA.svg'),
    },
    MC: {
      name: i18n._(msg`Monaco`),
      code: '+377',
      unicodeFlag: '🇲🇨',
      svgFlag: require('../../assets/icons/flags/MC.svg'),
    },
    ME: {
      name: i18n._(msg`Montenegro`),
      code: '+382',
      unicodeFlag: '🇲🇪',
      svgFlag: require('../../assets/icons/flags/ME.svg'),
    },
    MF: {
      name: i18n._(msg`Saint Martin (French part)`),
      code: '+590',
      unicodeFlag: '🇲🇫',
      svgFlag: require('../../assets/icons/flags/MF.svg'),
    },
    MG: {
      name: i18n._(msg`Madagascar`),
      code: '+261',
      unicodeFlag: '🇲🇬',
      svgFlag: require('../../assets/icons/flags/MG.svg'),
    },
    ML: {
      name: i18n._(msg`Mali`),
      code: '+223',
      unicodeFlag: '🇲🇱',
      svgFlag: require('../../assets/icons/flags/ML.svg'),
    },
    MM: {
      name: i18n._(msg`Myanmar`),
      code: '+95',
      unicodeFlag: '🇲🇲',
      svgFlag: require('../../assets/icons/flags/MM.svg'),
    },
    MN: {
      name: i18n._(msg`Mongolia`),
      code: '+976',
      unicodeFlag: '🇲🇳',
      svgFlag: require('../../assets/icons/flags/MN.svg'),
    },
    MO: {
      name: i18n._(msg`Macao`),
      code: '+853',
      unicodeFlag: '🇲🇴',
      svgFlag: require('../../assets/icons/flags/MO.svg'),
    },
    MQ: {
      name: i18n._(msg`Martinique`),
      code: '+596',
      unicodeFlag: '🇲🇶',
      svgFlag: require('../../assets/icons/flags/MQ.svg'),
    },
    MR: {
      name: i18n._(msg`Mauritania`),
      code: '+222',
      unicodeFlag: '🇲🇷',
      svgFlag: require('../../assets/icons/flags/MR.svg'),
    },
    MS: {
      name: i18n._(msg`Montserrat`),
      code: '+1664',
      unicodeFlag: '🇲🇸',
      svgFlag: require('../../assets/icons/flags/MS.svg'),
    },
    MT: {
      name: i18n._(msg`Malta`),
      code: '+356',
      unicodeFlag: '🇲🇹',
      svgFlag: require('../../assets/icons/flags/MT.svg'),
    },
    MU: {
      name: i18n._(msg`Mauritius`),
      code: '+230',
      unicodeFlag: '🇲🇺',
      svgFlag: require('../../assets/icons/flags/MU.svg'),
    },
    MV: {
      name: i18n._(msg`Maldives`),
      code: '+960',
      unicodeFlag: '🇲🇻',
      svgFlag: require('../../assets/icons/flags/MV.svg'),
    },
    MW: {
      name: i18n._(msg`Malawi`),
      code: '+265',
      unicodeFlag: '🇲🇼',
      svgFlag: require('../../assets/icons/flags/MW.svg'),
    },
    MX: {
      name: i18n._(msg`Mexico`),
      code: '+52',
      unicodeFlag: '🇲🇽',
      svgFlag: require('../../assets/icons/flags/MX.svg'),
    },
    MY: {
      name: i18n._(msg`Malaysia`),
      code: '+60',
      unicodeFlag: '🇲🇾',
      svgFlag: require('../../assets/icons/flags/MY.svg'),
    },
    MZ: {
      name: i18n._(msg`Mozambique`),
      code: '+258',
      unicodeFlag: '🇲🇿',
      svgFlag: require('../../assets/icons/flags/MZ.svg'),
    },
    NA: {
      name: i18n._(msg`Namibia`),
      code: '+264',
      unicodeFlag: '🇳🇦',
      svgFlag: require('../../assets/icons/flags/NA.svg'),
    },
    NC: {
      name: i18n._(msg`New Caledonia`),
      code: '+687',
      unicodeFlag: '🇳🇨',
      svgFlag: require('../../assets/icons/flags/NC.svg'),
    },
    NF: {
      name: i18n._(msg`Norfolk Island`),
      code: '+672',
      unicodeFlag: '🇳🇫',
      svgFlag: require('../../assets/icons/flags/NF.svg'),
    },
    NG: {
      name: i18n._(msg`Nigeria`),
      code: '+234',
      unicodeFlag: '🇳🇬',
      svgFlag: require('../../assets/icons/flags/NG.svg'),
    },
    NI: {
      name: i18n._(msg`Nicaragua`),
      code: '+505',
      unicodeFlag: '🇳🇮',
      svgFlag: require('../../assets/icons/flags/NI.svg'),
    },
    NO: {
      name: i18n._(msg`Norway`),
      code: '+47',
      unicodeFlag: '🇳🇴',
      svgFlag: require('../../assets/icons/flags/NO.svg'),
    },
    NP: {
      name: i18n._(msg`Nepal`),
      code: '+977',
      unicodeFlag: '🇳🇵',
      svgFlag: require('../../assets/icons/flags/NP.svg'),
    },
    NR: {
      name: i18n._(msg`Nauru`),
      code: '+674',
      unicodeFlag: '🇳🇷',
      svgFlag: require('../../assets/icons/flags/NR.svg'),
    },
    NU: {
      name: i18n._(msg`Niue`),
      code: '+683',
      unicodeFlag: '🇳🇺',
      svgFlag: require('../../assets/icons/flags/NU.svg'),
    },
    NZ: {
      name: i18n._(msg`New Zealand`),
      code: '+64',
      unicodeFlag: '🇳🇿',
      svgFlag: require('../../assets/icons/flags/NZ.svg'),
    },
    OM: {
      name: i18n._(msg`Oman`),
      code: '+968',
      unicodeFlag: '🇴🇲',
      svgFlag: require('../../assets/icons/flags/OM.svg'),
    },
    PA: {
      name: i18n._(msg`Panama`),
      code: '+507',
      unicodeFlag: '🇵🇦',
      svgFlag: require('../../assets/icons/flags/PA.svg'),
    },
    PE: {
      name: i18n._(msg`Peru`),
      code: '+51',
      unicodeFlag: '🇵🇪',
      svgFlag: require('../../assets/icons/flags/PE.svg'),
    },
    PF: {
      name: i18n._(msg`French Polynesia`),
      code: '+689',
      unicodeFlag: '🇵🇫',
      svgFlag: require('../../assets/icons/flags/PF.svg'),
    },
    PG: {
      name: i18n._(msg`Papua New Guinea`),
      code: '+675',
      unicodeFlag: '🇵🇬',
      svgFlag: require('../../assets/icons/flags/PG.svg'),
    },
    PK: {
      name: i18n._(msg`Pakistan`),
      code: '+92',
      unicodeFlag: '🇵🇰',
      svgFlag: require('../../assets/icons/flags/PK.svg'),
    },
    PL: {
      name: i18n._(msg`Poland`),
      code: '+48',
      unicodeFlag: '🇵🇱',
      svgFlag: require('../../assets/icons/flags/PL.svg'),
    },
    PM: {
      name: i18n._(msg`Saint Pierre and Miquelon`),
      code: '+508',
      unicodeFlag: '🇵🇲',
      svgFlag: require('../../assets/icons/flags/PM.svg'),
    },
    PN: {
      name: i18n._(msg`Pitcairn`),
      code: '+64',
      unicodeFlag: '🇵🇳',
      svgFlag: require('../../assets/icons/flags/PN.svg'),
    },
    PR: {
      name: i18n._(msg`Puerto Rico`),
      code: '+1',
      unicodeFlag: '🇵🇷',
      svgFlag: require('../../assets/icons/flags/PR.svg'),
    },
    PS: {
      name: i18n._(msg`Palestine, State of`),
      code: '+970',
      unicodeFlag: '🇵🇸',
      svgFlag: require('../../assets/icons/flags/PS.svg'),
    },
    PT: {
      name: i18n._(msg`Portugal`),
      code: '+351',
      unicodeFlag: '🇵🇹',
      svgFlag: require('../../assets/icons/flags/PT.svg'),
    },
    PW: {
      name: i18n._(msg`Palau`),
      code: '+680',
      unicodeFlag: '🇵🇼',
      svgFlag: require('../../assets/icons/flags/PW.svg'),
    },
    PY: {
      name: i18n._(msg`Paraguay`),
      code: '+595',
      unicodeFlag: '🇵🇾',
      svgFlag: require('../../assets/icons/flags/PY.svg'),
    },
    QA: {
      name: i18n._(msg`Qatar`),
      code: '+974',
      unicodeFlag: '🇶🇦',
      svgFlag: require('../../assets/icons/flags/QA.svg'),
    },
    RE: {
      name: i18n._(msg`Réunion`),
      code: '+262',
      unicodeFlag: '🇷🇪',
      svgFlag: require('../../assets/icons/flags/RE.svg'),
    },
    RO: {
      name: i18n._(msg`Romania`),
      code: '+40',
      unicodeFlag: '🇷🇴',
      svgFlag: require('../../assets/icons/flags/RO.svg'),
    },
    RS: {
      name: i18n._(msg`Serbia`),
      code: '+381',
      unicodeFlag: '🇷🇸',
      svgFlag: require('../../assets/icons/flags/RS.svg'),
    },
    RU: {
      name: i18n._(msg`Russia`),
      code: '+7',
      unicodeFlag: '🇷🇺',
      svgFlag: require('../../assets/icons/flags/RU.svg'),
    },
    RW: {
      name: i18n._(msg`Rwanda`),
      code: '+250',
      unicodeFlag: '🇷🇼',
      svgFlag: require('../../assets/icons/flags/RW.svg'),
    },
    SA: {
      name: i18n._(msg`Saudi Arabia`),
      code: '+966',
      unicodeFlag: '🇸🇦',
      svgFlag: require('../../assets/icons/flags/SA.svg'),
    },
    SB: {
      name: i18n._(msg`Solomon Islands`),
      code: '+677',
      unicodeFlag: '🇸🇧',
      svgFlag: require('../../assets/icons/flags/SB.svg'),
    },
    SC: {
      name: i18n._(msg`Seychelles`),
      code: '+248',
      unicodeFlag: '🇸🇨',
      svgFlag: require('../../assets/icons/flags/SC.svg'),
    },
    SE: {
      name: i18n._(msg`Sweden`),
      code: '+46',
      unicodeFlag: '🇸🇪',
      svgFlag: require('../../assets/icons/flags/SE.svg'),
    },
    SG: {
      name: i18n._(msg`Singapore`),
      code: '+65',
      unicodeFlag: '🇸🇬',
      svgFlag: require('../../assets/icons/flags/SG.svg'),
    },
    SH: {
      name: i18n._(msg`Saint Helena, Ascension and Tristan da Cunha`),
      code: '+290',
      unicodeFlag: '🇸🇭',
      svgFlag: require('../../assets/icons/flags/SH.svg'),
    },
    SI: {
      name: i18n._(msg`Slovenia`),
      code: '+386',
      unicodeFlag: '🇸🇮',
      svgFlag: require('../../assets/icons/flags/SI.svg'),
    },
    SJ: {
      name: i18n._(msg`Svalbard and Jan Mayen`),
      code: '+4779',
      unicodeFlag: '🇸🇯',
      svgFlag: require('../../assets/icons/flags/SJ.svg'),
    },
    SK: {
      name: i18n._(msg`Slovakia`),
      code: '+421',
      unicodeFlag: '🇸🇰',
      svgFlag: require('../../assets/icons/flags/SK.svg'),
    },
    SL: {
      name: i18n._(msg`Sierra Leone`),
      code: '+232',
      unicodeFlag: '🇸🇱',
      svgFlag: require('../../assets/icons/flags/SL.svg'),
    },
    SM: {
      name: i18n._(msg`Republic of San Marino`),
      code: '+378',
      unicodeFlag: '🇸🇲',
      svgFlag: require('../../assets/icons/flags/SM.svg'),
    },
    SN: {
      name: i18n._(msg`Senegal`),
      code: '+221',
      unicodeFlag: '🇸🇳',
      svgFlag: require('../../assets/icons/flags/SN.svg'),
    },
    SO: {
      name: i18n._(msg`Somalia`),
      code: '+252',
      unicodeFlag: '🇸🇴',
      svgFlag: require('../../assets/icons/flags/SO.svg'),
    },
    SR: {
      name: i18n._(msg`Suriname`),
      code: '+597',
      unicodeFlag: '🇸🇷',
      svgFlag: require('../../assets/icons/flags/SR.svg'),
    },
    SS: {
      name: i18n._(msg`South Sudan`),
      code: '+211',
      unicodeFlag: '🇸🇸',
      svgFlag: require('../../assets/icons/flags/SS.svg'),
    },
    ST: {
      name: i18n._(msg`Sao Tome and Principe`),
      code: '+239',
      unicodeFlag: '🇸🇹',
      svgFlag: require('../../assets/icons/flags/ST.svg'),
    },
    SV: {
      name: i18n._(msg`El Salvador`),
      code: '+503',
      unicodeFlag: '🇸🇻',
      svgFlag: require('../../assets/icons/flags/SV.svg'),
    },
    SX: {
      name: i18n._(msg`Sint Maarten (Dutch part)`),
      code: '+1721',
      unicodeFlag: '🇸🇽',
      svgFlag: require('../../assets/icons/flags/SX.svg'),
    },
    SY: {
      name: i18n._(msg`Syrian Arab Republic`),
      code: '+963',
      unicodeFlag: '🇸🇾',
      svgFlag: require('../../assets/icons/flags/SY.svg'),
    },
    TD: {
      name: i18n._(msg`Chad`),
      code: '+235',
      unicodeFlag: '🇹🇩',
      svgFlag: require('../../assets/icons/flags/TD.svg'),
    },
    TG: {
      name: i18n._(msg`Togo`),
      code: '+228',
      unicodeFlag: '🇹🇬',
      svgFlag: require('../../assets/icons/flags/TG.svg'),
    },
    TH: {
      name: i18n._(msg`Thailand`),
      code: '+66',
      unicodeFlag: '🇹🇭',
      svgFlag: require('../../assets/icons/flags/TH.svg'),
    },
    TJ: {
      name: i18n._(msg`Tajikistan`),
      code: '+992',
      unicodeFlag: '🇹🇯',
      svgFlag: require('../../assets/icons/flags/TJ.svg'),
    },
    TK: {
      name: i18n._(msg`Tokelau`),
      code: '+690',
      unicodeFlag: '🇹🇰',
      svgFlag: require('../../assets/icons/flags/TK.svg'),
    },
    TL: {
      name: i18n._(msg`Timor-Leste`),
      code: '+670',
      unicodeFlag: '🇹🇱',
      svgFlag: require('../../assets/icons/flags/TL.svg'),
    },
    TM: {
      name: i18n._(msg`Turkmenistan`),
      code: '+993',
      unicodeFlag: '🇹🇲',
      svgFlag: require('../../assets/icons/flags/TM.svg'),
    },
    TN: {
      name: i18n._(msg`Tunisia`),
      code: '+216',
      unicodeFlag: '🇹🇳',
      svgFlag: require('../../assets/icons/flags/TN.svg'),
    },
    TO: {
      name: i18n._(msg`Tonga`),
      code: '+676',
      unicodeFlag: '🇹🇴',
      svgFlag: require('../../assets/icons/flags/TO.svg'),
    },
    TR: {
      name: i18n._(msg`Turkey`),
      code: '+90',
      unicodeFlag: '🇹🇷',
      svgFlag: require('../../assets/icons/flags/TR.svg'),
    },
    TT: {
      name: i18n._(msg`Trinidad and Tobago`),
      code: '+868',
      unicodeFlag: '🇹🇹',
      svgFlag: require('../../assets/icons/flags/TT.svg'),
    },
    TV: {
      name: i18n._(msg`Tuvalu`),
      code: '+688',
      unicodeFlag: '🇹🇻',
      svgFlag: require('../../assets/icons/flags/TV.svg'),
    },
    TZ: {
      name: i18n._(msg`United Republic of Tanzania`),
      code: '+255',
      unicodeFlag: '🇹🇿',
      svgFlag: require('../../assets/icons/flags/TZ.svg'),
    },
    UA: {
      name: i18n._(msg`Ukraine`),
      code: '+380',
      unicodeFlag: '🇺🇦',
      svgFlag: require('../../assets/icons/flags/UA.svg'),
    },
    UG: {
      name: i18n._(msg`Uganda`),
      code: '+256',
      unicodeFlag: '🇺🇬',
      svgFlag: require('../../assets/icons/flags/UG.svg'),
    },
    US: {
      name: i18n._(msg`United States of America`),
      code: '+1',
      unicodeFlag: '🇺🇸',
      svgFlag: require('../../assets/icons/flags/US.svg'),
    },
    UY: {
      name: i18n._(msg`Uruguay`),
      code: '+598',
      unicodeFlag: '🇺🇾',
      svgFlag: require('../../assets/icons/flags/UY.svg'),
    },
    UZ: {
      name: i18n._(msg`Uzbekistan`),
      code: '+998',
      unicodeFlag: '🇺🇿',
      svgFlag: require('../../assets/icons/flags/UZ.svg'),
    },
    VC: {
      name: i18n._(msg`Saint Vincent and the Grenadines`),
      code: '+1784',
      unicodeFlag: '🇻🇨',
      svgFlag: require('../../assets/icons/flags/VC.svg'),
    },
    VE: {
      name: i18n._(msg`Venezuela (Bolivarian Republic of)`),
      code: '+58',
      unicodeFlag: '🇻🇪',
      svgFlag: require('../../assets/icons/flags/VE.svg'),
    },
    VG: {
      name: i18n._(msg`Virgin Islands (British)`),
      code: '+1284',
      unicodeFlag: '🇻🇬',
      svgFlag: require('../../assets/icons/flags/VG.svg'),
    },
    VI: {
      name: i18n._(msg`Virgin Islands (U.S.)`),
      code: '+1340',
      unicodeFlag: '🇻🇮',
      svgFlag: require('../../assets/icons/flags/VI.svg'),
    },
    VN: {
      name: i18n._(msg`Vietnam`),
      code: '+84',
      unicodeFlag: '🇻🇳',
      svgFlag: require('../../assets/icons/flags/VN.svg'),
    },
    VU: {
      name: i18n._(msg`Vanuatu`),
      code: '+678',
      unicodeFlag: '🇻🇺',
      svgFlag: require('../../assets/icons/flags/VU.svg'),
    },
    WF: {
      name: i18n._(msg`Wallis and Futuna`),
      code: '+681',
      unicodeFlag: '🇼🇫',
      svgFlag: require('../../assets/icons/flags/WF.svg'),
    },
    WS: {
      name: i18n._(msg`Samoa`),
      code: '+685',
      unicodeFlag: '🇼🇸',
      svgFlag: require('../../assets/icons/flags/WS.svg'),
    },
    YE: {
      name: i18n._(msg`Yemen`),
      code: '+967',
      unicodeFlag: '🇾🇪',
      svgFlag: require('../../assets/icons/flags/YE.svg'),
    },
    YT: {
      name: i18n._(msg`Mayotte`),
      code: '+262',
      unicodeFlag: '🇾🇹',
      svgFlag: require('../../assets/icons/flags/YT.svg'),
    },
    ZA: {
      name: i18n._(msg`South Africa`),
      code: '+27',
      unicodeFlag: '🇿🇦',
      svgFlag: require('../../assets/icons/flags/ZA.svg'),
    },
    ZM: {
      name: i18n._(msg`Zambia`),
      code: '+260',
      unicodeFlag: '🇿🇲',
      svgFlag: require('../../assets/icons/flags/ZM.svg'),
    },
    ZW: {
      name: i18n._(msg`Zimbabwe`),
      code: '+263',
      unicodeFlag: '🇿🇼',
      svgFlag: require('../../assets/icons/flags/ZW.svg'),
    },
    SZ: {
      name: i18n._(msg`Eswatini`),
      code: '+268',
      unicodeFlag: '🇸🇿',
      svgFlag: require('../../assets/icons/flags/SZ.svg'),
    },
    MK: {
      name: i18n._(msg`North Macedonia`),
      code: '+389',
      unicodeFlag: '🇲🇰',
      svgFlag: require('../../assets/icons/flags/MK.svg'),
    },
    PH: {
      name: i18n._(msg`Philippines`),
      code: '+63',
      unicodeFlag: '🇵🇭',
      svgFlag: require('../../assets/icons/flags/PH.svg'),
    },
    NL: {
      name: i18n._(msg`Netherlands`),
      code: '+31',
      unicodeFlag: '🇳🇱',
      svgFlag: require('../../assets/icons/flags/NL.svg'),
    },
    AE: {
      name: i18n._(msg`United Arab Emirates`),
      code: '+971',
      unicodeFlag: '🇦🇪',
      svgFlag: require('../../assets/icons/flags/AE.svg'),
    },
    MD: {
      name: i18n._(msg`Republic of Moldova`),
      code: '+373',
      unicodeFlag: '🇲🇩',
      svgFlag: require('../../assets/icons/flags/MD.svg'),
    },
    GM: {
      name: i18n._(msg`Gambia`),
      code: '+220',
      unicodeFlag: '🇬🇲',
      svgFlag: require('../../assets/icons/flags/GM.svg'),
    },
    DO: {
      name: i18n._(msg`Dominican Republic`),
      code: '+1',
      unicodeFlag: '🇩🇴',
      svgFlag: require('../../assets/icons/flags/DO.svg'),
    },
    SD: {
      name: i18n._(msg`Sudan`),
      code: '+249',
      unicodeFlag: '🇸🇩',
      svgFlag: require('../../assets/icons/flags/SD.svg'),
    },
    LA: {
      name: i18n._(msg`Lao People's Democratic Republic`),
      code: '+856',
      unicodeFlag: '🇱🇦',
      svgFlag: require('../../assets/icons/flags/LA.svg'),
    },
    TW: {
      name: i18n._(msg`Taiwan, Province of China`),
      code: '+886',
      unicodeFlag: '🇹🇼',
      svgFlag: require('../../assets/icons/flags/TW.svg'),
    },
    CG: {
      name: i18n._(msg`Republic of the Congo`),
      code: '+242',
      unicodeFlag: '🇨🇬',
      svgFlag: require('../../assets/icons/flags/CG.svg'),
    },
    CZ: {
      name: i18n._(msg`Czechia`),
      code: '+420',
      unicodeFlag: '🇨🇿',
      svgFlag: require('../../assets/icons/flags/CZ.svg'),
    },
    GB: {
      name: i18n._(msg`United Kingdom`),
      code: '+44',
      unicodeFlag: '🇬🇧',
      svgFlag: require('../../assets/icons/flags/GB.svg'),
    },
    NE: {
      name: i18n._(msg`Niger`),
      code: '+227',
      unicodeFlag: '🇳🇪',
      svgFlag: require('../../assets/icons/flags/NE.svg'),
    },
    CD: {
      name: i18n._(msg`Democratic Republic of the Congo`),
      code: '+243',
      unicodeFlag: '🇨🇩',
      svgFlag: require('../../assets/icons/flags/CD.svg'),
    },
    BS: {
      name: i18n._(msg`Commonwealth of The Bahamas`),
      code: '+1 242',
      unicodeFlag: '🇧🇸',
      svgFlag: require('../../assets/icons/flags/BS.svg'),
    },
    CC: {
      name: i18n._(msg`Cocos (Keeling) Islands`),
      code: '+61 891',
      unicodeFlag: '🇨🇨',
      svgFlag: require('../../assets/icons/flags/CC.svg'),
    },
    CF: {
      name: i18n._(msg`Central African Republic`),
      code: '+236',
      unicodeFlag: '🇨🇫',
      svgFlag: require('../../assets/icons/flags/CF.svg'),
    },
    CK: {
      name: i18n._(msg`Cook Islands`),
      code: '+682',
      unicodeFlag: '🇨🇰',
      svgFlag: require('../../assets/icons/flags/CK.svg'),
    },
    FK: {
      name: i18n._(msg`Falkland Islands`),
      code: '+500',
      unicodeFlag: '🇫🇰',
      svgFlag: require('../../assets/icons/flags/FK.svg'),
    },
    FO: {
      name: i18n._(msg`Faroe Islands`),
      code: '+298',
      unicodeFlag: '🇫🇴',
      svgFlag: require('../../assets/icons/flags/FO.svg'),
    },
    HM: {
      name: i18n._(msg`Territory of Heard Island and McDonald Islands`),
      code: '+672',
      unicodeFlag: '🇭🇲',
      svgFlag: require('../../assets/icons/flags/HM.svg'),
    },
    KM: {
      name: i18n._(msg`Comoros`),
      code: '+269',
      unicodeFlag: '🇰🇲',
      svgFlag: require('../../assets/icons/flags/KM.svg'),
    },
    KY: {
      name: i18n._(msg`Cayman Islands`),
      code: '+1 345',
      unicodeFlag: '🇰🇾',
      svgFlag: require('../../assets/icons/flags/KY.svg'),
    },
    MH: {
      name: i18n._(msg`Republic of the Marshall Islands`),
      code: '+692',
      unicodeFlag: '🇲🇭',
      svgFlag: require('../../assets/icons/flags/MH.svg'),
    },
    MP: {
      name: i18n._(msg`Commonwealth of the Northern Mariana Islands`),
      code: '+1 670',
      unicodeFlag: '🇲🇵',
      svgFlag: require('../../assets/icons/flags/MP.svg'),
    },
    TC: {
      name: i18n._(msg`Turks and Caicos Islands`),
      code: '+1 649',
      unicodeFlag: '🇹🇨',
      svgFlag: require('../../assets/icons/flags/TC.svg'),
    },
    TF: {
      name: i18n._(msg`French Southern and Antarctic Lands`),
      code: '+672',
      unicodeFlag: '🇹🇫',
      svgFlag: require('../../assets/icons/flags/TF.svg'),
    },
    UM: {
      name: i18n._(msg`United States Minor Outlying Islands`),
      code: '+1',
      unicodeFlag: '🇺🇲',
      svgFlag: require('../../assets/icons/flags/UM.svg'),
    },
    VA: {
      name: i18n._(msg`Holy See`),
      code: '+39',
      unicodeFlag: '🇻🇦',
      svgFlag: require('../../assets/icons/flags/VA.svg'),
    },
    XK: {
      name: i18n._(msg`Republic of Kosovo`),
      code: '+383',
      unicodeFlag: '🇽🇰',
      svgFlag: require('../../assets/icons/flags/XK.svg'),
    },
  }
}
