import { Platform } from "react-native";
import type { Theme } from "./ThemeContext";
import { colors } from "./styles";

export const solarplexTheme: Theme = {
  colorScheme: "light",
  palette: {
    default: {
      background: colors.white,
      backgroundLight: colors.gray1,
      text: colors.splx.neutral[40],
      textLight: colors.splx.primary[40],
      textInverted: colors.white,
      link: colors.splx.primary[40],
      border: colors.splx.neutral[10],
      borderDark: "#e0d9d9",
      icon: colors.gray4,
      // non-standard
      textVeryLight: colors.gray4,
      replyLine: colors.gray2,
      replyLineDot: colors.gray3,
      unreadNotifBg: "#ebf6ff",
      unreadNotifBorder: colors.blue1,
      postCtrl: "#71768A",
      brandText: "#0066FF",
      emptyStateIcon: "#B6B6C9",
    },
    primary: {
      background: colors.splx.primary[50],
      backgroundLight: colors.splx.primary[50],
      text: colors.white,
      textLight: colors.blue0,
      textInverted: colors.blue3,
      link: colors.blue0,
      border: colors.blue4,
      borderDark: colors.blue5,
      icon: colors.blue4,
    },
    secondary: {
      background: colors.green3,
      backgroundLight: colors.green2,
      text: colors.white,
      textLight: colors.green1,
      textInverted: colors.green4,
      link: colors.green1,
      border: colors.green4,
      borderDark: colors.green5,
      icon: colors.green4,
    },
    inverted: {
      background: colors.black,
      backgroundLight: colors.gray6,
      text: colors.white,
      textLight: colors.gray3,
      textInverted: colors.black,
      link: colors.blue2,
      border: colors.gray3,
      borderDark: colors.gray2,
      icon: colors.gray5,
    },
    error: {
      background: colors.red3,
      backgroundLight: colors.red2,
      text: colors.white,
      textLight: colors.red1,
      textInverted: colors.red3,
      link: colors.red1,
      border: colors.red4,
      borderDark: colors.red5,
      icon: colors.red4,
    },
  },
  shapes: {
    button: {
      // TODO
    },
    bigButton: {
      // TODO
    },
    smallButton: {
      // TODO
    },
  },
  typography: {
    "2xl-thin": {
      fontFamily: "Chirp",
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: "300",
    },
    "2xl": {
      fontFamily: "Chirp",
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: "400",
    },
    "2xl-medium": {
      fontFamily: "Chirp",
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "2xl-bold": {
      fontFamily: "Chirp",
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: "700",
    },
    "2xl-heavy": {
      fontFamily: "Chirp",
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: "800",
    },
    "xl-thin": {
      fontFamily: "Chirp",
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: "300",
    },
    xl: {
      fontFamily: "Chirp",
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: "400",
    },
    "xl-medium": {
      fontFamily: "Chirp",
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "xl-bold": {
      fontFamily: "Chirp",
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: "700",
    },
    "xl-heavy": {
      fontFamily: "Chirp",
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: "800",
    },
    "lg-thin": {
      fontFamily: "Chirp",
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: "300",
    },
    lg: {
      fontFamily: "Chirp",
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: "400",
    },
    "lg-medium": {
      fontFamily: "Chirp",
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "lg-bold": {
      fontFamily: "Chirp",
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: "700",
    },
    "lg-heavy": {
      fontFamily: "Chirp",
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: "800",
    },
    "md-thin": {
      fontFamily: "Chirp",
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: "300",
    },
    md: {
      fontFamily: "Chirp",
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: "400",
    },
    "md-medium": {
      fontFamily: "Chirp",
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "md-bold": {
      fontFamily: "Chirp",
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: "700",
    },
    "md-heavy": {
      fontFamily: "Chirp",
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: "800",
    },
    "sm-thin": {
      fontFamily: "Chirp",
      fontSize: 12,
      letterSpacing: 0.25,
      fontWeight: "300",
    },
    sm: {
      fontFamily: "Chirp",
      fontSize: 12,
      letterSpacing: 0.25,
      fontWeight: "400",
    },
    "sm-medium": {
      fontFamily: "Chirp",
      fontSize: 12,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "sm-bold": {
      fontFamily: "Chirp",
      fontSize: 12,
      letterSpacing: 0.25,
      fontWeight: "700",
    },
    "sm-heavy": {
      fontFamily: "Chirp",
      fontSize: 12,
      letterSpacing: 0.25,
      fontWeight: "800",
    },
    "xs-thin": {
      fontFamily: "Chirp",
      fontSize: 11,
      letterSpacing: 0.25,
      fontWeight: "300",
    },
    xs: {
      fontSize: 11,
      fontFamily: "Chirp",
      letterSpacing: 0.25,
      fontWeight: "400",
    },
    "xs-medium": {
      fontFamily: "Chirp",
      fontSize: 11,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "xs-bold": {
      fontFamily: "Chirp",
      fontSize: 11,
      letterSpacing: 0.25,
      fontWeight: "700",
    },
    "xs-heavy": {
      fontFamily: "Chirp",
      fontSize: 11,
      letterSpacing: 0.25,
      fontWeight: "800",
    },

    "title-2xl": {
      fontFamily: "Chirp",
      fontSize: 32,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "title-xl": {
      fontFamily: "Chirp",
      fontSize: 26,
      letterSpacing: 0.25,
      fontWeight: "500",
    },
    "title-lg": {
      fontFamily: "Chirp",
      fontSize: 20,
      fontWeight: "500",
    },
    title: {
      fontFamily: "Chirp",
      fontWeight: "500",
      fontSize: 18,
      letterSpacing: 0.15,
    },
    "title-sm": {
      fontFamily: "Chirp",
      fontWeight: "bold",
      fontSize: 15,
      letterSpacing: 0.15,
    },
    "post-text": {
      fontFamily: "Chirp",
      fontSize: 14,
      letterSpacing: 0.2,
      fontWeight: "400",
    },
    "post-text-lg": {
      fontFamily: "Chirp",
      fontSize: 20,
      letterSpacing: 0.4,
      fontWeight: "400",
    },
    "button-lg": {
      fontFamily: "Chirp",
      fontWeight: "500",
      fontSize: 16,
      letterSpacing: 0.5,
    },
    button: {
      fontFamily: "Chirp",
      fontWeight: "500",
      fontSize: 12,
      letterSpacing: 0.5,
    },
    mono: {
      fontSize: 12,
      fontFamily: Platform.OS === "android" ? "Chirp" : "Chirp",
    },
  },
};
