const productionSuggestedFollows = [
  'john',
  'visakanv ',
  'saz ',
  'steph ',
  'ratzlaff ',
  'beth',
  'weisser ',
  'katherine ',
  'annagat',
  'josh',
  'lurkshark',
  'amir',
  'amyxzh',
  'danielle ',
  'jack-frazee',
  'vibes',
  'cat',
  'yuriy',
  'alvinreyes',
  'skoot',
  'patricia',
  'ara4n',
  'case',
  'armand',
  'ivan',
  'nicholas',
  'kelsey',
  'ericlee',
  'emily',
  'jake',
  'jennijuju',
  'ian5v',
  'bnewbold',
  'chris',
  'mtclai',
  'willscott',
  'michael',
  'kwkroeger',
  'broox',
  'iamrosewang',
  'jack-morrison',
  'pwang',
  'martin',
  'jack',
  'dan',
  'why',
  'divy',
  'jay',
  'paul',
].map(handle => `${handle}.bsky.social`)

const stagingSuggestedFollows = ['arcalinea', 'paul', 'paul2'].map(
  handle => `${handle}.staging.bsky.dev`,
)

const devSuggestedFollows = ['alice', 'bob', 'carla'].map(
  handle => `${handle}.test`,
)

export {
  productionSuggestedFollows,
  stagingSuggestedFollows,
  devSuggestedFollows,
}
