plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.blueskygifview'
version = '0.5.0'

android {
  namespace "expo.modules.blueskygifview"
  defaultConfig {
    versionCode 1
    versionName "0.5.0"
  }
}

dependencies {
  implementation 'androidx.appcompat:appcompat:1.6.1'

  // Keep glide version up to date with expo-image so that we don't have duplicate deps
  implementation 'com.github.bumptech.glide:glide:4.13.2'
}
