# Important: when a two letter code is ambiguous, we need
# to manually map it to the full locale code. This is done
# in the Crowdin language mapping config here:
# https://bluesky.crowdin.com/u/projects/1/languages
{
  "project_id": "1",
  "base_url": "https://bluesky.api.crowdin.com",
  "base_path": ".",
  "preserve_hierarchy": true,
  "files": [
    {
      "source": "/src/locale/locales/en/messages.po",
      "translation": "/src/locale/locales/%two_letters_code%/messages.po"
    }
  ]
}
