FROM node:22.13-alpine3.20

WORKDIR /app

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
COPY /patches /app/patches
COPY /lingui.config.js /app/lingui.config.js
COPY /src/locale/locales /app/src/locale/locales

RUN pwd
RUN cd /app
RUN yarn

COPY . /app

ENV EXPO_PUBLIC_APPVIEW_DID=${APPVIEW_DID}

CMD ["yarn", "web"]
