import {deepStrictEqual, equal} from 'node:assert/strict'
import {mkdirSync, writeFileSync} from 'node:fs'
import {join} from 'node:path'
import {pathToFileURL} from 'node:url'

import {simulatePreparation} from './prepare.mjs'

export const demoInput = Object.freeze({
  releaseVersion: '1.133.0',
  sourceSha: 'a'.repeat(40),
  packageVersion: '1.133.0',
  expoVersion: '1.133.0',
  runtimeVersion: '1.133.0',
  changelog: '- Improve search results\n- Fix video playback',
})

/** Deterministic, self-checking fixtures used by the CLI, tests, and PR artifact. */
export function runDemo() {
  const fresh = simulatePreparation(demoInput)
  equal(fresh.status, 'complete')
  deepStrictEqual(
    fresh.events.map(event => event.action),
    ['create', 'create', 'create', 'create'],
  )
  const scenarios = [{name: 'First preparation', result: fresh}]
  const retry = simulatePreparation(demoInput, fresh.state)
  deepStrictEqual(retry.state, fresh.state)
  deepStrictEqual(
    retry.events.map(event => event.action),
    ['reuse', 'reuse', 'reuse', 'reuse'],
  )
  scenarios.push({name: 'Retry after success', result: retry})
  for (let stopAfter = 0; stopAfter <= 4; stopAfter++) {
    const interrupted = simulatePreparation(demoInput, {}, {stopAfter})
    equal(interrupted.status, 'interrupted')
    const resumed = simulatePreparation(demoInput, interrupted.state)
    deepStrictEqual(resumed.state, fresh.state)
    deepStrictEqual(
      resumed.events.map(event => event.action),
      Array.from({length: 4}, (_, index) =>
        index < stopAfter ? 'reuse' : 'create',
      ),
    )
    scenarios.push({
      name: `Interrupted after ${stopAfter} steps`,
      result: interrupted,
    })
    scenarios.push({name: `Resume after ${stopAfter} steps`, result: resumed})
  }
  const conflicts = [
    ['Source moved', {...demoInput, sourceSha: 'b'.repeat(40)}, fresh.state],
    [
      'Changelog changed',
      {...demoInput, changelog: '- Different candidate'},
      fresh.state,
    ],
    [
      'Branch belongs to another candidate',
      demoInput,
      {
        ...fresh.state,
        branch: {...fresh.state.branch, candidateId: 'simulation:other'},
      },
    ],
    [
      'Tag belongs to another candidate',
      demoInput,
      {
        ...fresh.state,
        tag: {...fresh.state.tag, candidateId: 'simulation:other'},
      },
    ],
    [
      'Release already published',
      demoInput,
      {...fresh.state, release: {...fresh.state.release, draft: false}},
    ],
    ['Candidate provenance missing', demoInput, {tag: fresh.state.tag}],
  ]
  for (const [name, input, snapshot] of conflicts) {
    const result = simulatePreparation(input, snapshot)
    equal(result.status, 'blocked')
    deepStrictEqual(result.events, [])
    deepStrictEqual(result.state, snapshot)
    scenarios.push({name, result})
  }
  for (const field of ['packageVersion', 'expoVersion', 'runtimeVersion']) {
    let error
    try {
      simulatePreparation({...demoInput, [field]: '1.134.0'})
    } catch (caught) {
      error = caught.message
    }
    equal(error, `${field} must match releaseVersion.`)
    scenarios.push({
      name: `${field} mismatch`,
      result: {
        mode: 'simulation',
        status: 'blocked',
        conflicts: [error],
        events: [],
      },
    })
  }
  return {schemaVersion: 1, mode: 'simulation', input: demoInput, scenarios}
}

export function renderReport(demo) {
  const sections = demo.scenarios.map(({name, result}) => {
    const lines = result.events.map(
      event => `- ${event.action}: ${event.resource}`,
    )
    if (result.conflicts.length)
      lines.push(...result.conflicts.map(conflict => `- Blocked: ${conflict}`))
    if (!lines.length)
      lines.push(
        '- Stopped before the first step; no simulated resource changed.',
      )
    return `## ${name}\n\nOutcome: **${result.status}**\n\n${lines.join('\n')}`
  })
  return `# Release preparation demo\n\nGenerated by \`node scripts/release/prepare-demo.mjs\`. All ${demo.scenarios.length} scenarios are self-checked.\n\nThis is a simulation using fixed fixtures, not the state of a real release. Branches, tags, candidate commits, and GitHub Releases exist only in memory. No Git commands, network requests, builds, translation operations, or publications are performed. Candidate IDs prefixed with \`simulation:\` are not Git SHAs.\n\nThe input source SHA is a fixture. The generated release document and draft body show the proposed content; the JSON report includes each simulated resource snapshot. Translation updates, real commit creation, and live GitHub integration remain unimplemented.\n\n${sections.join('\n\n')}\n`
}

/** Write only to a new caller-selected output directory; never replace a report. */
export function writeDemo(directory) {
  const demo = runDemo()
  mkdirSync(directory, {recursive: false})
  const initial = demo.scenarios[0].result
  for (const [filename, contents] of Object.entries({
    'README.md': renderReport(demo),
    'report.json': `${JSON.stringify(demo, null, 2)}\n`,
    [initial.identity.filename]: initial.document,
    'github-release-body.md': `${initial.publicChangelog}\n`,
  })) {
    writeFileSync(join(directory, filename), contents, {flag: 'wx'})
  }
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  try {
    const args = process.argv.slice(2)
    if (args.length === 0) process.stdout.write(renderReport(runDemo()))
    else if (args.length === 2 && args[0] === '--output') writeDemo(args[1])
    else
      throw new Error(
        'Usage: node scripts/release/prepare-demo.mjs [--output <new-directory>] (simulation only)',
      )
  } catch (error) {
    console.error(error.message)
    process.exitCode = 1
  }
}
