// This file is generated by pnpm icons:generate. Do not edit.

import {createSVG} from '../TEMPLATE'

export const EnvelopeNotification_Filled_Corner2_Rounded = createSVG({
  elements: [
    {
      fill: 'currentColor',
      stroke: 'none',
      type: 'path',
      d: 'M1 10.419A15.7 15.7 0 0 0 11 14c2.451 0 4.771-.56 6.84-1.559a5.6 5.6 0 0 0 3.16-.249v6.058A2.75 2.75 0 0 1 18.25 21H3.75A2.75 2.75 0 0 1 1 18.25v-7.831ZM13.808 5a5.6 5.6 0 0 0-.37 2c0 1.931.983 3.633 2.477 4.63-1.532.563-3.188.87-4.915.87A14.2 14.2 0 0 1 1 8.402V7.75A2.75 2.75 0 0 1 3.75 5h10.058ZM19 3a4 4 0 1 1 0 8 4 4 0 0 1 0-8Z',
    },
  ],
  viewBox: '0 0 24 24',
})
