export type Gate =
  // Keep this alphabetic please.
  | 'debug_show_feedcontext'
  | 'explore_page_profile_card_social_proof'
  | 'native_pwi_disabled'
  | 'new_user_guided_tour'
  | 'new_user_progress_guide'
  | 'onboarding_minimum_interests'
  | 'session_withproxy_fix'
  | 'show_avi_follow_button'
  | 'show_follow_back_label_v2'
  | 'suggested_feeds_interstitial'
  | 'ungroup_follow_backs'
  | 'video_debug'
  | 'videos'
