import {type AtpAgent} from '@atproto/api'

import {LINK_META_PROXY} from '#/lib/constants'
import {getGiphyMetaUri} from '#/lib/strings/embed-player'
import {parseStarterPackUri} from '#/lib/strings/starter-pack'
import {isBskyAppUrl} from '#/lib/strings/url-helpers'

export enum LikelyType {
  HTML,
  Text,
  Image,
  Video,
  Audio,
  AtpData,
  Other,
}

export interface LinkMeta {
  error?: string
  likelyType: LikelyType
  url: string
  title?: string
  description?: string
  image?: string
}

export async function getLinkMeta(
  agent: AtpAgent,
  url: string,
  timeout = 15e3,
): Promise<LinkMeta> {
  if (isBskyAppUrl(url) && !parseStarterPackUri(url)) {
    return {
      likelyType: LikelyType.AtpData,
      url,
    }
  }

  let urlp
  let shouldFollowRedirect = false
  try {
    urlp = new URL(url)

    // Get Giphy meta uri if this is any form of giphy link
    const giphyMetaUri = getGiphyMetaUri(urlp)
    if (giphyMetaUri) {
      url = giphyMetaUri
      urlp = new URL(url)
    }
    // follow redirects for soundcloud shortlinks
    // QUESTION - do we want to follow redirects in other cases? -sfn
    shouldFollowRedirect = urlp.hostname === 'on.soundcloud.com'
  } catch (e) {
    return {
      error: 'Invalid URL',
      likelyType: LikelyType.Other,
      url,
    }
  }
  const likelyType = getLikelyType(urlp)
  const meta: LinkMeta = {
    likelyType,
    url,
  }
  const htmlExemptedHostnames: string[] = ['storage.courtlistener.com']
  const isExemptedFromHtmlCheck = htmlExemptedHostnames.includes(urlp.hostname)
  // Skip early return only for hosts exempted from the HTML check
  if (likelyType !== LikelyType.HTML && !isExemptedFromHtmlCheck) {
    return meta
  }

  const controller = new AbortController()
  const to = setTimeout(() => controller.abort(), timeout || 5e3)

  try {
    const response = await fetch(
      `${LINK_META_PROXY(agent.serviceUrl.toString() || '')}${encodeURIComponent(
        url,
      )}`,
      {signal: controller.signal},
    )

    const body = await response.json()

    if (body.error !== '') {
      throw new Error(body.error)
    }

    meta.description = body.description
    meta.image = body.image
    meta.title = body.title
    if (shouldFollowRedirect) {
      meta.url = body.url
    }
  } catch (e) {
    // failed
    console.error(e)
    meta.error = e instanceof Error ? e.toString() : 'Failed to fetch link'
  } finally {
    clearTimeout(to)
  }

  return meta
}

/**
 * Get the likely type of content based on URL file extension.
 */
export function getLikelyType(url: URL | string): LikelyType {
  if (typeof url === 'string') {
    try {
      url = new URL(url)
    } catch (e) {
      return LikelyType.Other
    }
  }

  const ext = url.pathname.split('.').pop() || ''

  switch (ext) {
    case '':
    case 'html':
    case 'shtml':
    case 'htm':
    case 'php':
    case 'asp':
    case 'aspx':
    case 'xhtml':
      return LikelyType.HTML

    case '3dml':
    case 'appcache':
    case 'asm':
    case 'c':
    case 'cc':
    case 'coffee':
    case 'conf':
    case 'cpp':
    case 'css':
    case 'csv':
    case 'curl':
    case 'cxx':
    case 'dcurl':
    case 'def':
    case 'dic':
    case 'dsc':
    case 'etx':
    case 'f':
    case 'f77':
    case 'f90':
    case 'flx':
    case 'fly':
    case 'for':
    case 'ged':
    case 'gv':
    case 'h':
    case 'hbs':
    case 'hh':
    case 'htc':
    case 'ics':
    case 'ifb':
    case 'in':
    case 'ini':
    case 'jad':
    case 'jade':
    case 'java':
    case 'jsx':
    case 'less':
    case 'list':
    case 'litcoffee':
    case 'log':
    case 'lua':
    case 'man':
    case 'manifest':
    case 'markdown':
    case 'mcurl':
    case 'md':
    case 'mdx':
    case 'me':
    case 'mkd':
    case 'mml':
    case 'ms':
    case 'n3':
    case 'nfo':
    case 'opml':
    case 'org':
    case 'p':
    case 'pas':
    case 'pde':
    case 'roff':
    case 'rtf':
    case 'rtx':
    case 's':
    case 'sass':
    case 'scss':
    case 'scurl':
    case 'sfv':
    case 'sgm':
    case 'sgml':
    case 'shex':
    case 'slim':
    case 'slm':
    case 'spdx':
    case 'spot':
    case 'styl':
    case 'stylus':
    case 'sub':
    case 't':
    case 'text':
    case 'tr':
    case 'tsv':
    case 'ttl':
    case 'txt':
    case 'uri':
    case 'uris':
    case 'urls':
    case 'uu':
    case 'vcard':
    case 'vcf':
    case 'vcs':
    case 'vtt':
    case 'wml':
    case 'wmls':
    case 'xml':
    case 'yaml':
    case 'yml':
    case 'ymp':
      return LikelyType.Text

    case '3ds':
    case 'apng':
    case 'avif':
    case 'azv':
    case 'b16':
    case 'bmp':
    case 'btif':
    case 'cgm':
    case 'cmx':
    case 'dds':
    case 'djv':
    case 'djvu':
    case 'drle':
    case 'dwg':
    case 'dxf':
    case 'emf':
    case 'exr':
    case 'fbs':
    case 'fh':
    case 'fh4':
    case 'fh5':
    case 'fh7':
    case 'fhc':
    case 'fits':
    case 'fpx':
    case 'fst':
    case 'g3':
    case 'gif':
    case 'heic':
    case 'heics':
    case 'heif':
    case 'heifs':
    case 'hej2':
    case 'hsj2':
    case 'ico':
    case 'ief':
    case 'jhc':
    case 'jls':
    case 'jng':
    case 'jp2':
    case 'jpe':
    case 'jpeg':
    case 'jpf':
    case 'jpg':
    case 'jpg2':
    case 'jph':
    case 'jpx':
    case 'jxr':
    case 'jxra':
    case 'jxrs':
    case 'jxs':
    case 'jxsc':
    case 'jxsi':
    case 'jxss':
    case 'ktx':
    case 'ktx2':
    case 'mdi':
    case 'mmr':
    case 'npx':
    case 'pbm':
    case 'pct':
    case 'pcx':
    case 'pgm':
    case 'pic':
    case 'png':
    case 'pnm':
    case 'ppm':
    case 'psd':
    case 'pti':
    case 'ras':
    case 'rgb':
    case 'rlc':
    case 'sgi':
    case 'sid':
    case 'svg':
    case 'svgz':
    case 't38':
    case 'tap':
    case 'tfx':
    case 'tga':
    case 'tif':
    case 'tiff':
    case 'uvg':
    case 'uvi':
    case 'uvvg':
    case 'uvvi':
    case 'vtf':
    case 'wbmp':
    case 'wdp':
    case 'webp':
    case 'wmf':
    case 'xbm':
    case 'xif':
    case 'xpm':
    case 'xwd':
      return LikelyType.Image

    case '3g2':
    case '3gp':
    case '3gpp':
    case 'asf':
    case 'asx':
    case 'avi':
    case 'dvb':
    case 'f4v':
    case 'fli':
    case 'flv':
    case 'fvt':
    case 'h261':
    case 'h263':
    case 'h264':
    case 'jpgm':
    case 'jpgv':
    case 'jpm':
    case 'm1v':
    case 'm2v':
    case 'm4s':
    case 'm4u':
    case 'm4v':
    case 'mj2':
    case 'mjp2':
    case 'mk3d':
    case 'mks':
    case 'mkv':
    case 'mng':
    case 'mov':
    case 'movie':
    case 'mp4':
    case 'mp4v':
    case 'mpe':
    case 'mpeg':
    case 'mpg':
    case 'mpg4':
    case 'mxu':
    case 'ogv':
    case 'pyv':
    case 'qt':
    case 'smv':
    case 'ts':
    case 'uvh':
    case 'uvm':
    case 'uvp':
    case 'uvs':
    case 'uvu':
    case 'uvv':
    case 'uvvh':
    case 'uvvm':
    case 'uvvp':
    case 'uvvs':
    case 'uvvu':
    case 'uvvv':
    case 'viv':
    case 'vob':
    case 'webm':
    case 'wm':
    case 'wmv':
    case 'wmx':
    case 'wvx':
      return LikelyType.Video

    case 'aac':
    case 'adp':
    case 'aif':
    case 'aifc':
    case 'aiff':
    case 'amr':
    case 'au':
    case 'caf':
    case 'dra':
    case 'dts':
    case 'dtshd':
    case 'ecelp4800':
    case 'ecelp7470':
    case 'ecelp9600':
    case 'eol':
    case 'flac':
    case 'kar':
    case 'lvp':
    case 'm2a':
    case 'm3a':
    case 'm3u':
    case 'm4a':
    case 'mid':
    case 'midi':
    case 'mka':
    case 'mp2':
    case 'mp2a':
    case 'mp3':
    case 'mp4a':
    case 'mpga':
    case 'mxmf':
    case 'oga':
    case 'ogg':
    case 'opus':
    case 'pya':
    case 'ra':
    case 'ram':
    case 'rip':
    case 'rmi':
    case 'rmp':
    case 's3m':
    case 'sil':
    case 'snd':
    case 'spx':
    case 'uva':
    case 'uvva':
    case 'wav':
    case 'wax':
    case 'weba':
    case 'wma':
    case 'xm':
      return LikelyType.Audio

    case '123':
    case '1km':
    case '3mf':
    case '7z':
    case 'aab':
    case 'aam':
    case 'aas':
    case 'abw':
    case 'ac':
    case 'acc':
    case 'ace':
    case 'acu':
    case 'acutc':
    case 'aep':
    case 'afm':
    case 'afp':
    case 'age':
    case 'ahead':
    case 'ai':
    case 'air':
    case 'ait':
    case 'ami':
    case 'apk':
    case 'application':
    case 'apr':
    case 'arc':
    case 'arj':
    case 'asc':
    case 'aso':
    case 'atc':
    case 'atom':
    case 'atomcat':
    case 'atomdeleted':
    case 'atomsvc':
    case 'atx':
    case 'aw':
    case 'azf':
    case 'azs':
    case 'azw':
    case 'bat':
    case 'bcpio':
    case 'bdf':
    case 'bdm':
    case 'bdoc':
    case 'bed':
    case 'bh2':
    case 'bin':
    case 'blb':
    case 'blorb':
    case 'bmi':
    case 'bmml':
    case 'book':
    case 'box':
    case 'boz':
    case 'bpk':
    case 'bsp':
    case 'buffer':
    case 'bz':
    case 'bz2':
    case 'c11amc':
    case 'c11amz':
    case 'c4d':
    case 'c4f':
    case 'c4g':
    case 'c4p':
    case 'c4u':
    case 'cab':
    case 'cap':
    case 'car':
    case 'cat':
    case 'cb7':
    case 'cba':
    case 'cbr':
    case 'cbt':
    case 'cbz':
    case 'cco':
    case 'cct':
    case 'ccxml':
    case 'cdbcmsg':
    case 'cdf':
    case 'cdfx':
    case 'cdkey':
    case 'cdmia':
    case 'cdmic':
    case 'cdmid':
    case 'cdmio':
    case 'cdmiq':
    case 'cdx':
    case 'cdxml':
    case 'cdy':
    case 'cer':
    case 'cfs':
    case 'chat':
    case 'chm':
    case 'chrt':
    case 'cif':
    case 'cii':
    case 'cil':
    case 'cjs':
    case 'cla':
    case 'class':
    case 'clkk':
    case 'clkp':
    case 'clkt':
    case 'clkw':
    case 'clkx':
    case 'clp':
    case 'cmc':
    case 'cmdf':
    case 'cml':
    case 'cmp':
    case 'cod':
    case 'com':
    case 'cpio':
    case 'cpt':
    case 'crd':
    case 'crl':
    case 'crt':
    case 'crx':
    case 'cryptonote':
    case 'csh':
    case 'csl':
    case 'csml':
    case 'csp':
    case 'cst':
    case 'cu':
    case 'cww':
    case 'cxt':
    case 'dae':
    case 'daf':
    case 'dart':
    case 'dataless':
    case 'davmount':
    case 'dbf':
    case 'dbk':
    case 'dcr':
    case 'dd2':
    case 'ddd':
    case 'ddf':
    case 'deb':
    case 'deploy':
    case 'der':
    case 'dfac':
    case 'dgc':
    case 'dir':
    case 'dis':
    case 'disposition-notification':
    case 'dist':
    case 'distz':
    case 'dll':
    case 'dmg':
    case 'dmp':
    case 'dms':
    case 'dna':
    case 'doc':
    case 'docm':
    case 'docx':
    case 'dot':
    case 'dotm':
    case 'dotx':
    case 'dp':
    case 'dpg':
    case 'dssc':
    case 'dtb':
    case 'dtd':
    case 'dump':
    case 'dvi':
    case 'dwd':
    case 'dwf':
    case 'dxp':
    case 'dxr':
    case 'ear':
    case 'ecma':
    case 'edm':
    case 'edx':
    case 'efif':
    case 'ei6':
    case 'elc':
    case 'eml':
    case 'emma':
    case 'emotionml':
    case 'emz':
    case 'eot':
    case 'eps':
    case 'epub':
    case 'es':
    case 'es3':
    case 'esa':
    case 'esf':
    case 'et3':
    case 'eva':
    case 'evy':
    case 'exe':
    case 'exi':
    case 'exp':
    case 'ext':
    case 'ez':
    case 'ez2':
    case 'ez3':
    case 'fcdt':
    case 'fcs':
    case 'fdf':
    case 'fdt':
    case 'fe_launch':
    case 'fg5':
    case 'fgd':
    case 'fig':
    case 'flo':
    case 'flw':
    case 'fm':
    case 'fnc':
    case 'fo':
    case 'frame':
    case 'fsc':
    case 'ftc':
    case 'fti':
    case 'fxp':
    case 'fxpl':
    case 'fzs':
    case 'g2w':
    case 'g3w':
    case 'gac':
    case 'gam':
    case 'gbr':
    case 'gca':
    case 'gdl':
    case 'gdoc':
    case 'geo':
    case 'geojson':
    case 'gex':
    case 'ggb':
    case 'ggt':
    case 'ghf':
    case 'gim':
    case 'glb':
    case 'gltf':
    case 'gml':
    case 'gmx':
    case 'gnumeric':
    case 'gph':
    case 'gpx':
    case 'gqf':
    case 'gqs':
    case 'gram':
    case 'gramps':
    case 'gre':
    case 'grv':
    case 'grxml':
    case 'gsf':
    case 'gsheet':
    case 'gslides':
    case 'gtar':
    case 'gtm':
    case 'gtw':
    case 'gxf':
    case 'gxt':
    case 'gz':
    case 'hal':
    case 'hbci':
    case 'hdd':
    case 'hdf':
    case 'held':
    case 'hjson':
    case 'hlp':
    case 'hpgl':
    case 'hpid':
    case 'hps':
    case 'hqx':
    case 'htke':
    case 'hvd':
    case 'hvp':
    case 'hvs':
    case 'i2g':
    case 'icc':
    case 'ice':
    case 'icm':
    case 'ifm':
    case 'iges':
    case 'igl':
    case 'igm':
    case 'igs':
    case 'igx':
    case 'iif':
    case 'img':
    case 'imp':
    case 'ims':
    case 'ink':
    case 'inkml':
    case 'install':
    case 'iota':
    case 'ipfix':
    case 'ipk':
    case 'irm':
    case 'irp':
    case 'iso':
    case 'itp':
    case 'its':
    case 'ivp':
    case 'ivu':
    case 'jam':
    case 'jar':
    case 'jardiff':
    case 'jisp':
    case 'jlt':
    case 'jnlp':
    case 'joda':
    case 'js':
    case 'json':
    case 'json5':
    case 'jsonld':
    case 'jsonml':
    case 'karbon':
    case 'kdbx':
    case 'key':
    case 'kfo':
    case 'kia':
    case 'kml':
    case 'kmz':
    case 'kne':
    case 'knp':
    case 'kon':
    case 'kpr':
    case 'kpt':
    case 'kpxx':
    case 'ksp':
    case 'ktr':
    case 'ktz':
    case 'kwd':
    case 'kwt':
    case 'lasxml':
    case 'latex':
    case 'lbd':
    case 'lbe':
    case 'les':
    case 'lgr':
    case 'lha':
    case 'link66':
    case 'list3820':
    case 'listafp':
    case 'lnk':
    case 'lostxml':
    case 'lrf':
    case 'lrm':
    case 'ltf':
    case 'luac':
    case 'lwp':
    case 'lzh':
    case 'm13':
    case 'm14':
    case 'm21':
    case 'm3u8':
    case 'm4p':
    case 'ma':
    case 'mads':
    case 'maei':
    case 'mag':
    case 'maker':
    case 'map':
    case 'mar':
    case 'mathml':
    case 'mb':
    case 'mbk':
    case 'mbox':
    case 'mc1':
    case 'mcd':
    case 'mdb':
    case 'mesh':
    case 'meta4':
    case 'metalink':
    case 'mets':
    case 'mfm':
    case 'mft':
    case 'mgp':
    case 'mgz':
    case 'mie':
    case 'mif':
    case 'mime':
    case 'mjs':
    case 'mlp':
    case 'mmd':
    case 'mmf':
    case 'mny':
    case 'mobi':
    case 'mods':
    case 'mp21':
    case 'mp4s':
    case 'mpc':
    case 'mpd':
    case 'mpkg':
    case 'mpm':
    case 'mpn':
    case 'mpp':
    case 'mpt':
    case 'mpy':
    case 'mqy':
    case 'mrc':
    case 'mrcx':
    case 'mscml':
    case 'mseed':
    case 'mseq':
    case 'msf':
    case 'msg':
    case 'msh':
    case 'msi':
    case 'msl':
    case 'msm':
    case 'msp':
    case 'msty':
    case 'mtl':
    case 'mts':
    case 'mus':
    case 'musd':
    case 'musicxml':
    case 'mvb':
    case 'mvt':
    case 'mwf':
    case 'mxf':
    case 'mxl':
    case 'mxml':
    case 'mxs':
    case 'n-gage':
    case 'nb':
    case 'nbp':
    case 'nc':
    case 'ncx':
    case 'ngdat':
    case 'nitf':
    case 'nlu':
    case 'nml':
    case 'nnd':
    case 'nns':
    case 'nnw':
    case 'nq':
    case 'nsc':
    case 'nsf':
    case 'nt':
    case 'ntf':
    case 'numbers':
    case 'nzb':
    case 'oa2':
    case 'oa3':
    case 'oas':
    case 'obd':
    case 'obgx':
    case 'obj':
    case 'oda':
    case 'odb':
    case 'odc':
    case 'odf':
    case 'odft':
    case 'odg':
    case 'odi':
    case 'odm':
    case 'odp':
    case 'ods':
    case 'odt':
    case 'ogex':
    case 'ogx':
    case 'omdoc':
    case 'onepkg':
    case 'onetmp':
    case 'onetoc':
    case 'onetoc2':
    case 'opf':
    case 'oprc':
    case 'osf':
    case 'osfpvg':
    case 'osm':
    case 'otc':
    case 'otf':
    case 'otg':
    case 'oth':
    case 'oti':
    case 'otp':
    case 'ots':
    case 'ott':
    case 'ova':
    case 'ovf':
    case 'owl':
    case 'oxps':
    case 'oxt':
    case 'p10':
    case 'p12':
    case 'p7b':
    case 'p7c':
    case 'p7m':
    case 'p7r':
    case 'p7s':
    case 'p8':
    case 'pac':
    case 'pages':
    case 'paw':
    case 'pbd':
    case 'pcap':
    case 'pcf':
    case 'pcl':
    case 'pclxl':
    case 'pcurl':
    case 'pdb':
    case 'pdf':
    case 'pem':
    case 'pfa':
    case 'pfb':
    case 'pfm':
    case 'pfr':
    case 'pfx':
    case 'pgn':
    case 'pgp':
    case 'pkg':
    case 'pki':
    case 'pkipath':
    case 'pkpass':
    case 'pl':
    case 'plb':
    case 'plc':
    case 'plf':
    case 'pls':
    case 'pm':
    case 'pml':
    case 'portpkg':
    case 'pot':
    case 'potm':
    case 'potx':
    case 'ppam':
    case 'ppd':
    case 'pps':
    case 'ppsm':
    case 'ppsx':
    case 'ppt':
    case 'pptm':
    case 'pptx':
    case 'pqa':
    case 'prc':
    case 'pre':
    case 'prf':
    case 'provx':
    case 'ps':
    case 'psb':
    case 'psf':
    case 'pskcxml':
    case 'ptid':
    case 'pub':
    case 'pvb':
    case 'pwn':
    case 'qam':
    case 'qbo':
    case 'qfx':
    case 'qps':
    case 'qwd':
    case 'qwt':
    case 'qxb':
    case 'qxd':
    case 'qxl':
    case 'qxt':
    case 'raml':
    case 'rapd':
    case 'rar':
    case 'rcprofile':
    case 'rdf':
    case 'rdz':
    case 'relo':
    case 'rep':
    case 'res':
    case 'rif':
    case 'ris':
    case 'rl':
    case 'rld':
    case 'rm':
    case 'rms':
    case 'rmvb':
    case 'rnc':
    case 'rng':
    case 'roa':
    case 'rp9':
    case 'rpm':
    case 'rpss':
    case 'rpst':
    case 'rq':
    case 'rs':
    case 'rsat':
    case 'rsd':
    case 'rsheet':
    case 'rss':
    case 'run':
    case 'rusd':
    case 'saf':
    case 'sbml':
    case 'sc':
    case 'scd':
    case 'scm':
    case 'scq':
    case 'scs':
    case 'sda':
    case 'sdc':
    case 'sdd':
    case 'sdkd':
    case 'sdkm':
    case 'sdp':
    case 'sdw':
    case 'sea':
    case 'see':
    case 'seed':
    case 'sema':
    case 'semd':
    case 'semf':
    case 'senmlx':
    case 'sensmlx':
    case 'ser':
    case 'setpay':
    case 'setreg':
    case 'sfd-hdstx':
    case 'sfs':
    case 'sgl':
    case 'sh':
    case 'shar':
    case 'shf':
    case 'sieve':
    case 'sig':
    case 'silo':
    case 'sis':
    case 'sisx':
    case 'sit':
    case 'sitx':
    case 'siv':
    case 'skd':
    case 'skm':
    case 'skp':
    case 'skt':
    case 'sldm':
    case 'sldx':
    case 'sls':
    case 'slt':
    case 'sm':
    case 'smf':
    case 'smi':
    case 'smil':
    case 'smzip':
    case 'snf':
    case 'so':
    case 'spc':
    case 'spf':
    case 'spl':
    case 'spp':
    case 'spq':
    case 'sql':
    case 'src':
    case 'srt':
    case 'sru':
    case 'srx':
    case 'ssdl':
    case 'sse':
    case 'ssf':
    case 'ssml':
    case 'st':
    case 'stc':
    case 'std':
    case 'stf':
    case 'sti':
    case 'stk':
    case 'stl':
    case 'stpx':
    case 'stpxz':
    case 'stpz':
    case 'str':
    case 'stw':
    case 'sus':
    case 'susp':
    case 'sv4cpio':
    case 'sv4crc':
    case 'svc':
    case 'svd':
    case 'swa':
    case 'swf':
    case 'swi':
    case 'swidtag':
    case 'sxc':
    case 'sxd':
    case 'sxg':
    case 'sxi':
    case 'sxm':
    case 'sxw':
    case 't3':
    case 'taglet':
    case 'tao':
    case 'tar':
    case 'tcap':
    case 'tcl':
    case 'td':
    case 'teacher':
    case 'tei':
    case 'teicorpus':
    case 'tex':
    case 'texi':
    case 'texinfo':
    case 'tfi':
    case 'tfm':
    case 'thmx':
    case 'tk':
    case 'tmo':
    case 'toml':
    case 'torrent':
    case 'tpl':
    case 'tpt':
    case 'tra':
    case 'trig':
    case 'trm':
    case 'tsd':
    case 'ttc':
    case 'ttf':
    case 'ttml':
    case 'twd':
    case 'twds':
    case 'txd':
    case 'txf':
    case 'u32':
    case 'u8dsn':
    case 'u8hdr':
    case 'u8mdn':
    case 'u8msg':
    case 'ubj':
    case 'udeb':
    case 'ufd':
    case 'ufdl':
    case 'ulx':
    case 'umj':
    case 'unityweb':
    case 'uoml':
    case 'usdz':
    case 'ustar':
    case 'utz':
    case 'uvd':
    case 'uvf':
    case 'uvt':
    case 'uvvd':
    case 'uvvf':
    case 'uvvt':
    case 'uvvx':
    case 'uvvz':
    case 'uvx':
    case 'uvz':
    case 'vbox':
    case 'vbox-extpack':
    case 'vcd':
    case 'vcg':
    case 'vcx':
    case 'vdi':
    case 'vds':
    case 'vhd':
    case 'vis':
    case 'vmdk':
    case 'vor':
    case 'vox':
    case 'vrml':
    case 'vsd':
    case 'vsf':
    case 'vss':
    case 'vst':
    case 'vsw':
    case 'vtu':
    case 'vxml':
    case 'w3d':
    case 'wad':
    case 'wadl':
    case 'war':
    case 'wasm':
    case 'wbs':
    case 'wbxml':
    case 'wcm':
    case 'wdb':
    case 'webapp':
    case 'webmanifest':
    case 'wg':
    case 'wgt':
    case 'wks':
    case 'wmd':
    case 'wmlc':
    case 'wmlsc':
    case 'wmz':
    case 'woff':
    case 'woff2':
    case 'wpd':
    case 'wpl':
    case 'wps':
    case 'wqd':
    case 'wri':
    case 'wrl':
    case 'wsc':
    case 'wsdl':
    case 'wspolicy':
    case 'wtb':
    case 'x32':
    case 'x3d':
    case 'x3db':
    case 'x3dbz':
    case 'x3dv':
    case 'x3dvz':
    case 'x3dz':
    case 'x_b':
    case 'x_t':
    case 'xaml':
    case 'xap':
    case 'xar':
    case 'xav':
    case 'xbap':
    case 'xbd':
    case 'xca':
    case 'xcs':
    case 'xdf':
    case 'xdm':
    case 'xdp':
    case 'xdssc':
    case 'xdw':
    case 'xel':
    case 'xenc':
    case 'xer':
    case 'xfdf':
    case 'xfdl':
    case 'xht':
    case 'xhvml':
    case 'xla':
    case 'xlam':
    case 'xlc':
    case 'xlf':
    case 'xlm':
    case 'xls':
    case 'xlsb':
    case 'xlsm':
    case 'xlsx':
    case 'xlt':
    case 'xltm':
    case 'xltx':
    case 'xlw':
    case 'xns':
    case 'xo':
    case 'xop':
    case 'xpi':
    case 'xpl':
    case 'xpr':
    case 'xps':
    case 'xpw':
    case 'xpx':
    case 'xsd':
    case 'xsl':
    case 'xslt':
    case 'xsm':
    case 'xspf':
    case 'xul':
    case 'xvm':
    case 'xvml':
    case 'xyz':
    case 'xz':
    case 'yang':
    case 'yin':
    case 'z1':
    case 'z2':
    case 'z3':
    case 'z4':
    case 'z5':
    case 'z6':
    case 'z7':
    case 'z8':
    case 'zaz':
    case 'zip':
    case 'zir':
    case 'zirz':
    case 'zmm':
      return LikelyType.Other

    default:
      // Unknown extension - assume HTML
      return LikelyType.HTML
  }
}
