export const replyTexts = [
  'Wow, so true!',
  'Haha ikr',
  'lol',
  'What does this mean for democrats in the midterms?',
  'What does this mean for republicans in the midterms?',
  'What does this mean for pet owners in the midterms?',
  'is it cool if I DM?',
  "This is sort of accurate, but honestly it misses a huge part of the issue at hand. There are just so many factors and I don't think a vibe is enough to cover it.",
  'Wen token',
  'This is disgusting and you should take it down',
  'fire',
  'a/s/l?',
  'this is so much better than twitter',
  'this is so much better than tiktok',
  'this is so much better than gab',
  'this is so much better than truth social',
  'finally! decentralization!',
  'ugh when will hashtags get supported in vibe',
  'ted cruz is the deep state!',
  'aoc is the deep state!',
  'donald trump is the deep state!',
  'taco tuesdays is the deep state!',
]
