import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { View } from 'react-native';
import { atoms as a, useTheme } from '#/alf';
import { Text } from '#/components/Typography';
import { Palette } from './Palette';
export function Theming() {
    var t = useTheme();
    return (_jsxs(View, { style: [t.atoms.bg, a.gap_lg, a.p_xl], children: [_jsx(Palette, {}), _jsx(Text, { style: [a.font_semi_bold, a.pt_xl, a.px_md], children: "theme.atoms.text" }), _jsx(View, { style: [a.flex_1, t.atoms.border_contrast_high, a.border_t] }), _jsx(Text, { style: [a.font_semi_bold, t.atoms.text_contrast_high, a.px_md], children: "theme.atoms.text_contrast_high" }), _jsx(View, { style: [a.flex_1, t.atoms.border_contrast_medium, a.border_t] }), _jsx(Text, { style: [a.font_semi_bold, t.atoms.text_contrast_medium, a.px_md], children: "theme.atoms.text_contrast_medium" }), _jsx(View, { style: [a.flex_1, t.atoms.border_contrast_low, a.border_t] }), _jsx(Text, { style: [a.font_semi_bold, t.atoms.text_contrast_low, a.px_md], children: "theme.atoms.text_contrast_low" }), _jsx(View, { style: [a.flex_1, t.atoms.border_contrast_low, a.border_t] }), _jsxs(View, { style: [a.w_full, a.gap_md], children: [_jsx(View, { style: [t.atoms.bg, a.justify_center, a.p_md], children: _jsx(Text, { children: "theme.atoms.bg" }) }), _jsx(View, { style: [t.atoms.bg_contrast_25, a.justify_center, a.p_md], children: _jsx(Text, { children: "theme.atoms.bg_contrast_25" }) }), _jsx(View, { style: [t.atoms.bg_contrast_50, a.justify_center, a.p_md], children: _jsx(Text, { children: "theme.atoms.bg_contrast_50" }) }), _jsx(View, { style: [t.atoms.bg_contrast_100, a.justify_center, a.p_md], children: _jsx(Text, { children: "theme.atoms.bg_contrast_100" }) }), _jsx(View, { style: [t.atoms.bg_contrast_200, a.justify_center, a.p_md], children: _jsx(Text, { children: "theme.atoms.bg_contrast_200" }) }), _jsx(View, { style: [t.atoms.bg_contrast_300, a.justify_center, a.p_md], children: _jsx(Text, { children: "theme.atoms.bg_contrast_300" }) })] })] }));
}
