package main

import (
	"bytes"
	"encoding/json"
	"regexp"
	"strings"
	"testing"

	"github.com/bluesky-social/social-app/bskyweb"
	"github.com/flosch/pongo2/v6"
)

// renderTemplate executes a template by name with the given context and
// returns the rendered output. Uses the same renderer plumbing as the live
// server so we exercise the real template loader.
//
// post.html and profile.html both extend base.html, which {% include %}s
// templates/scripts.html — a file generated by the React/Vite web build.
// When that file is absent (e.g. running `go test` in a fresh checkout
// without a prior `yarn build-web`), template loading fails. Skip rather
// than fail in that case.
func renderTemplate(t *testing.T, name string, ctx pongo2.Context) string {
	t.Helper()
	if _, err := bskyweb.TemplateFS.ReadFile("templates/scripts.html"); err != nil {
		t.Skip("templates/scripts.html not present (run yarn build-web first); skipping render tests")
	}
	r := NewRenderer("templates/", &bskyweb.TemplateFS, false)
	tmpl, err := r.TemplateSet.FromCache(name)
	if err != nil {
		t.Fatalf("template load %q: %v", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.ExecuteWriter(ctx, &buf); err != nil {
		t.Fatalf("template execute %q: %v", name, err)
	}
	return buf.String()
}

var jsonLDRe = regexp.MustCompile(`(?s)<script type="application/ld\+json">(.*?)</script>`)

// extractJSONLD pulls out the body of the <script type="application/ld+json">
// block from rendered HTML. Asserts the block exists.
func extractJSONLD(t *testing.T, html string) string {
	t.Helper()
	m := jsonLDRe.FindStringSubmatch(html)
	if m == nil {
		t.Fatalf("no application/ld+json script tag in rendered HTML:\n%s", html)
	}
	return strings.TrimSpace(m[1])
}

func TestRenderPost_EmitsJSONLD(t *testing.T) {
	pv := makePostView("alice.bsky.social", "did:plc:alice", "abc123", "hello")
	ld, err := buildPostJSONLD(pv, nil, "https://bsky.app/profile/alice.bsky.social/post/abc123", hideEmbedLabels)
	if err != nil {
		t.Fatal(err)
	}
	html := renderTemplate(t, "post.html", pongo2.Context{
		"postView":     pv,
		"requestURI":   "https://bsky.app/profile/alice.bsky.social/post/abc123",
		"canonicalURL": "https://bsky.app/profile/alice.bsky.social/post/abc123",
		"postJSONLD":   ld,
	})

	body := extractJSONLD(t, html)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(body), &parsed); err != nil {
		t.Fatalf("rendered JSON-LD does not parse: %v\n%s", err, body)
	}
	if parsed["@type"] != "WebPage" {
		t.Errorf("expected WebPage envelope, got %v", parsed["@type"])
	}
	// Verify canonical link is the handle-form URL (not the request URI
	// canonicalized).
	if !strings.Contains(html, `<link rel="canonical" href="https://bsky.app/profile/alice.bsky.social/post/abc123" />`) {
		t.Errorf("canonical link missing or wrong:\n%s", html)
	}
}

func TestRenderPost_OGImageMatchesJSONLD(t *testing.T) {
	thumb1 := "https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:alice/abc@jpeg"
	thumb2 := "https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:alice/def@jpeg"
	pv := makePostView("alice.bsky.social", "did:plc:alice", "abc123", "look", withImages(thumb1, thumb2))
	ld, _ := buildPostJSONLD(pv, nil, "https://bsky.app/profile/alice.bsky.social/post/abc123", hideEmbedLabels)
	html := renderTemplate(t, "post.html", pongo2.Context{
		"postView":     pv,
		"requestURI":   "https://bsky.app/profile/alice.bsky.social/post/abc123",
		"canonicalURL": "https://bsky.app/profile/alice.bsky.social/post/abc123",
		"postJSONLD":   ld,
		// Mirrors what server.go puts in: og:image meta tags use imgThumbUrls.
		"imgThumbUrls": []string{thumb1, thumb2},
	})

	// og:image must use the same URLs as JSON-LD's image[] (Google byte-equality requirement).
	if !strings.Contains(html, `<meta property="og:image" content="`+thumb1+`">`) {
		t.Errorf("og:image[0] not found in rendered HTML")
	}
	body := extractJSONLD(t, html)
	var parsed map[string]any
	_ = json.Unmarshal([]byte(body), &parsed)
	main := parsed["mainEntity"].(map[string]any)
	imgs := main["image"].([]any)
	if imgs[0] != thumb1 || main["thumbnailUrl"] != thumb1 {
		t.Errorf("JSON-LD image strings drifted from og:image; image[0]=%v thumbnailUrl=%v",
			imgs[0], main["thumbnailUrl"])
	}
}

func TestRenderPost_FallsBackToCanonicalizeFilter(t *testing.T) {
	// When canonicalURL is not set, template should fall back to
	// requestURI|canonicalize_url.
	pv := makePostView("alice.bsky.social", "did:plc:alice", "abc123", "hi")
	ld, _ := buildPostJSONLD(pv, nil, "u", hideEmbedLabels)
	html := renderTemplate(t, "post.html", pongo2.Context{
		"postView":   pv,
		"requestURI": "https://bsky.app/profile/alice.bsky.social/post/abc123?utm=foo",
		"postJSONLD": ld,
	})
	if !strings.Contains(html, `<link rel="canonical" href="https://bsky.app/profile/alice.bsky.social/post/abc123" />`) {
		t.Errorf("expected canonicalize_url filter to strip query; got:\n%s", html)
	}
}

func TestRenderProfile_EmitsJSONLD(t *testing.T) {
	pv := newProfileViewDetailed()
	ld, err := buildProfileJSONLD(pv, nil, hideEmbedLabels)
	if err != nil {
		t.Fatal(err)
	}
	html := renderTemplate(t, "profile.html", pongo2.Context{
		"profileView":   pv,
		"requestURI":    "https://bsky.app/profile/alice.bsky.social",
		"canonicalURL":  "https://bsky.app/profile/alice.bsky.social",
		"profileJSONLD": ld,
	})

	body := extractJSONLD(t, html)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(body), &parsed); err != nil {
		t.Fatalf("rendered JSON-LD does not parse: %v\n%s", err, body)
	}
	if parsed["@type"] != "ProfilePage" {
		t.Errorf("expected ProfilePage, got %v", parsed["@type"])
	}
}

// TestRenderProfile_AuthRequiredEmitsJSONLD confirms that auth-required
// profiles still emit ProfilePage / Person structured data (without
// hasPart). Previously this regressed when WebProfile was refactored to
// short-circuit before buildProfileJSONLD; the regression test guards
// against re-introducing that.
func TestRenderProfile_AuthRequiredEmitsJSONLD(t *testing.T) {
	pv := newProfileViewDetailed()
	ld, err := buildProfileJSONLD(pv, nil, hideEmbedLabels)
	if err != nil {
		t.Fatal(err)
	}
	html := renderTemplate(t, "profile.html", pongo2.Context{
		"profileView":   pv,
		"requestURI":    "https://bsky.app/profile/alice.bsky.social",
		"requiresAuth":  true,
		"profileJSONLD": ld,
	})

	body := extractJSONLD(t, html)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(body), &parsed); err != nil {
		t.Fatalf("rendered JSON-LD does not parse: %v\n%s", err, body)
	}
	if parsed["@type"] != "ProfilePage" {
		t.Errorf("expected ProfilePage, got %v", parsed["@type"])
	}
	if _, present := parsed["hasPart"]; present {
		t.Errorf("auth-required profile should not have hasPart")
	}
}

// TestRenderPost_OGUrlMatchesCanonical confirms that og:url and
// <link rel="canonical"> emit the same URL when canonicalURL is set, so
// social cards and search engines see a consistent reference.
func TestRenderPost_OGUrlMatchesCanonical(t *testing.T) {
	pv := makePostView("alice.bsky.social", "did:plc:alice", "abc123", "hi")
	ld, _ := buildPostJSONLD(pv, nil, "u", hideEmbedLabels)
	canonical := "https://bsky.app/profile/alice.bsky.social/post/abc123"
	html := renderTemplate(t, "post.html", pongo2.Context{
		"postView":     pv,
		"requestURI":   "https://bsky.app/profile/did:plc:alice/post/abc123",
		"canonicalURL": canonical,
		"postJSONLD":   ld,
	})
	if !strings.Contains(html, `<meta property="og:url" content="`+canonical+`">`) {
		t.Errorf("og:url should equal canonical URL when set; got:\n%s", html)
	}
	if !strings.Contains(html, `<link rel="canonical" href="`+canonical+`" />`) {
		t.Errorf("canonical link missing or wrong:\n%s", html)
	}
	// Inverse: the request URI (DID form) should NOT appear as og:url.
	if strings.Contains(html, `<meta property="og:url" content="https://bsky.app/profile/did:plc:alice/post/abc123">`) {
		t.Errorf("og:url should not echo DID-form request URI when canonical is set")
	}
}
