allowBuilds:
  "better-sqlite3": false # doesn't work on node24! TODO: enable once dev-env supports node24. this PR cannot be merged until then
  "core-js": true
  "protobufjs": true
  "sharp": true
  "unrs-resolver": true
