// This file is generated by pnpm icons:generate. Do not edit.

import {Attie_Filled_Corner0_Rounded as CanonicalAttie_Filled_Corner0_Rounded} from './community/Attie'

/** @deprecated Import Attie_Filled_Corner0_Rounded from `#/components/icons/community/Attie` instead. */
export const Attie_Filled_Corner0_Rounded =
  CanonicalAttie_Filled_Corner0_Rounded
