// This file is generated by pnpm icons:generate. Do not edit.

import {StarterPack_Stroke2_Corner0_Rounded as CanonicalStarterPack_Stroke2_Corner0_Rounded} from './brands/StarterPack'
import {StarterPackMultiPathLarge as CanonicalStarterPackMultiPathLarge} from './brands/StarterPack'

/** @deprecated Import StarterPack_Stroke2_Corner0_Rounded from `#/components/icons/brands/StarterPack` instead. */
export const StarterPack_Stroke2_Corner0_Rounded =
  CanonicalStarterPack_Stroke2_Corner0_Rounded

/** @deprecated Import StarterPackMultiPathLarge from `#/components/icons/brands/StarterPack` instead. */
export const StarterPackMultiPathLarge = CanonicalStarterPackMultiPathLarge
