# This is the project version with the correct keys
name: Build and deploy container app to Azure Web App - elideus-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Build Web App with Yarn
      run: |
        export NVM_DIR=$HOME/.nvm
        mkdir -p $NVM_DIR

        wget --output-document=/tmp/nvm-install.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        bash /tmp/nvm-install.sh

        . $NVM_DIR/nvm.sh
        
        nvm install 20
        nvm use 20
        
        npm install --global yarn
        
        yarn install
        yarn intl:build
        yarn build-web

    - name: Stage React Web App
      run: |
        mkdir -p backend/static/
        [ -d dist ] && cp -r dist/* backend/static/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://elideus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_78ce49491a7740b187cb15f7e08f5179 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_92251d1cd4334d13bb10c05baa6deb8a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: elideus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_78ce49491a7740b187cb15f7e08f5179 }}/elideus/social-app:${{ github.sha }}
        file: ./Dockerfile-azure

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elideus-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_54b3a80aca92433f92feb30b606965e5 }}
        images: 'elideus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_78ce49491a7740b187cb15f7e08f5179 }}/elideus/social-app:${{ github.sha }}'
